/** Authored mission catalogue. Unit means the CURRENT course, never the legacy folder number. */
const mission = (
  id,
  unit,
  family,
  title,
  role,
  question,
  product,
  choices,
  evidence,
  twist,
  defaults,
  classic,
) => ({
  id,
  unit,
  family,
  title,
  role,
  question,
  product,
  choices,
  evidence,
  twist,
  defaults,
  classic,
});
export const PROJECTS = [
  mission(
    "discovery",
    1,
    "discovery",
    "Make Math Belong",
    "Design a welcoming math exhibit.",
    "How can one pattern invite several ways of thinking?",
    "A pattern exhibit with two strategies and a visitor challenge.",
    ["Tile mural", "Team badge", "Pocket puzzle"],
    [
      "Show the first four stages as drawings or groups.",
      "Explain two ways to count the same stage.",
      "Write a question a visitor can solve and explain.",
    ],
    "A visitor reads your rule differently. Test both interpretations at a new stage.",
    { a: 4, b: 3, c: 5 },
    null,
  ),
  mission(
    "pre-unit-a",
    0,
    "division",
    "Launch Day Supply Depot",
    "Be the supply chief for a school launch day.",
    "How can you supply everyone without ordering more than you can afford?",
    "A supply order with a seating plan, cut list and budget defense.",
    ["Welcome festival", "Art build day", "Team challenge"],
    [
      "Draw how seats are grouped and label the leftover people.",
      "Show equivalent decimal division, not only a calculator result.",
      "Model fraction division with equal lengths. Explain which leftovers can be used.",
    ],
    "Twelve more people arrive. Change the headcount, test your order, and explain what must change.",
    { a: 146, b: 24, c: 58.5, d: 2.25, e: 12, f: 0.75 },
    "/math/pre-unit/projects/version-a/",
  ),
  mission(
    "unit-1-a",
    6,
    "division",
    "Block Party Planner",
    "Plan a neighborhood event.",
    "Can every guest get a seat while supplies stay within budget?",
    "A party plan the setup team could follow.",
    ["Neighborhood games", "Outdoor art show", "Welcome picnic"],
    [
      "Sketch a seating plan that includes every guest.",
      "Show the cost of complete supply packs and the money left.",
      "Draw a ribbon-cut model and label each piece.",
    ],
    "An extra table is unavailable. Change the seats per table and explain the new order.",
    { a: 157, b: 12, c: 67.5, d: 2.5, e: 15, f: 0.75 },
    "/math/unit-1/projects/version-a/",
  ),
  mission(
    "unit-1-b",
    6,
    "division",
    "Build-a-Bot Budget Lab",
    "Lead a robotics supply team.",
    "How can your crew pack hardware and cut wire with less waste?",
    "A robotics build order and a labeled wire-cut diagram.",
    ["Rescue robot", "Recycling robot", "Art robot"],
    [
      "Draw hardware bins and show why a partially full bin still counts.",
      "Compare the supply budget with the cost of full sensor packs.",
      "Explain how many wire pieces fit and what remains.",
    ],
    "A wire segment must be longer. Change its length and explain the effect on usable pieces.",
    { a: 235, b: 18, c: 84, d: 3.5, e: 16.5, f: 0.75 },
    "/math/unit-1/projects/version-b/",
  ),
  mission(
    "unit-1-c",
    6,
    "division",
    "Deep Space Supply Mission",
    "Serve as a space-station logistics officer.",
    "Will your evacuation and supply plan work for the whole crew?",
    "A mission-control briefing with three checked orders.",
    ["Research station", "Lunar outpost", "Orbital repair crew"],
    [
      "Account for every crew member in your pod plan.",
      "Show fuel-pack division and check with multiplication.",
      "Use a fraction model for tether lengths. Interpret the leftover.",
    ],
    "A shuttle loses four seats. Revise the capacity and defend your evacuation plan.",
    { a: 173, b: 16, c: 96, d: 3.2, e: 18, f: 0.75 },
    "/math/unit-1/projects/version-c/",
  ),
  mission(
    "unit-2-a",
    2,
    "statistics",
    "Class Data Detective",
    "Investigate a fictional maker-club trial.",
    "What does a typical build time hide about the group?",
    "An evidence poster with a dot plot and a cautious recommendation.",
    ["Paper bridge test", "Puzzle trial", "Marble-run test"],
    [
      "Ask a statistical question that expects different answers.",
      "Label the display, units, center and spread.",
      "Explain whose results your sample can describe and one limitation.",
    ],
    "One unusually long trial is added. Change the last value and compare mean, median and spread.",
    { data: "4, 6, 6, 8, 10, 14" },
    "/math/unit-2/projects/version-a/",
  ),
  mission(
    "unit-2-b",
    2,
    "statistics",
    "Weather Decision Desk",
    "Advise a fictional outdoor club.",
    "Which summary helps a team plan for changing conditions?",
    "A weather briefing using a labeled sample, not a forecast.",
    ["Outdoor rehearsal", "Garden club", "Field-day setup"],
    [
      "State a statistical question about the provided simulated temperatures.",
      "Explain why a dot plot, histogram or box plot fits your question.",
      "Describe what this small sample cannot predict.",
    ],
    "Replace the warmest day with a more extreme value. Decide whether your original recommendation still holds.",
    { data: "16, 18, 18, 20, 22, 26" },
    "/math/unit-2/projects/version-b/",
  ),
  mission(
    "unit-3-a",
    3,
    "ratio",
    "Smoothie Bar Designer",
    "Create a fictional smoothie stand.",
    "How can you scale a signature blend without changing its taste?",
    "A recipe card, ratio table and purchasing recommendation.",
    ["Fruit-forward blend", "Team-color blend", "Low-waste blend"],
    [
      "Draw a double number line or tape diagram for your recipe.",
      "Distinguish the ingredient-to-ingredient ratio from the ingredient-to-total ratio.",
      "Show equivalent ratios and a fair unit-price comparison.",
    ],
    "Demand doubles. Change the batch multiplier and explain what stays proportional.",
    { a: 3, b: 2, c: 6, d: 12, e: 8, f: 15, g: 12 },
    "/math/unit-3/projects/version-a/",
  ),
  mission(
    "unit-3-b",
    3,
    "ratio",
    "Sports Stats Scout",
    "Scout two fictional players.",
    "How can you make a fair comparison when players have different opportunities?",
    "A scouting card with rates, a prediction table and a limitation.",
    ["Basketball scorer", "Soccer passer", "Track team"],
    [
      "Label what each part of your performance ratio counts.",
      "Scale opportunities and outcomes by the same factor.",
      "Compare points per game and explain why a prediction is not a guarantee.",
    ],
    "The number of games doubles. Test the model and explain why real performance may vary.",
    { a: 18, b: 2, c: 5, d: 84, e: 6, f: 110, g: 10 },
    "/math/unit-3/projects/version-b/",
  ),
  mission(
    "unit-4-a",
    4,
    "percent",
    "Pop-Up Shop Owner",
    "Open a fictional school pop-up.",
    "Which offer is attractive and still fits a customer’s budget?",
    "A price tag, percent model and itemized receipt.",
    ["Sticker studio", "Book swap supplies", "Craft stall"],
    [
      "Represent the discount with a 100-grid or bar.",
      "Show the discounted price before calculating tax.",
      "Explain the fraction, decimal and percent forms of the offer.",
    ],
    "The discount increases by five percentage points. Test the new receipt and explain the change.",
    { a: 40, b: 20, c: 6, d: 50 },
    "/math/unit-4/projects/version-a/",
  ),
  mission(
    "unit-4-b",
    4,
    "percent",
    "Smart Shopper Showdown",
    "Help a fictional club choose a purchase.",
    "Does the biggest percent discount always mean the best decision?",
    "A comparison memo and a receipt that stays under a budget.",
    ["Art supplies", "Game-day gear", "Reading corner"],
    [
      "Draw a percent bar for the original price.",
      "Explain why tax uses the sale price in this model.",
      "Compare with a second design and explain price versus usefulness.",
    ],
    "The starting price rises by $10. Keep or change the offer and justify your choice.",
    { a: 60, b: 25, c: 5, d: 65 },
    "/math/unit-4/projects/version-b/",
  ),
  mission(
    "unit-5-a",
    5,
    "area",
    "Dream Room Designer",
    "Design a public reading lounge.",
    "How can your floor plan create useful space within a materials budget?",
    "A labeled composite plan, storage model and cost proposal.",
    ["Quiet reading", "Collaborative making", "Game-and-puzzle corner"],
    [
      "Decompose the floor into a rectangle and triangle without overlap.",
      "Show a second way to verify the area.",
      "Draw the storage prism and distinguish square from cubic units.",
    ],
    "The triangular nook needs twice its original height. Revise your plan and compare costs.",
    { a: 6, b: 4, c: 3, d: 2, e: 8, f: 2, g: 1, h: 1.5 },
    "/math/unit-5/projects/version-a/",
  ),
  mission(
    "unit-5-b",
    5,
    "area",
    "Room Makeover Budget",
    "Redesign a fictional community studio.",
    "Which layout balances space, materials and storage?",
    "A makeover bid with a floor plan and a storage-box net.",
    ["Art room", "Music lounge", "Community workshop"],
    [
      "Label base and perpendicular height on the triangular area.",
      "Find the net area and volume of your storage box.",
      "Explain what the flooring price includes and excludes.",
    ],
    "The material price rises by $2 per square unit. Revise a dimension to limit the cost increase.",
    { a: 7, b: 5, c: 4, d: 3, e: 6, f: 2, g: 1.5, h: 1 },
    "/math/unit-5/projects/version-b/",
  ),
  mission(
    "unit-6-a",
    6,
    "expressions",
    "Game Studio Scoring Engine",
    "Design a fair score system.",
    "Can two different-looking rules reward the same play?",
    "A scoring rulebook with test cases and an equivalence proof.",
    ["Exploration game", "Cooperative rescue", "Puzzle quest"],
    [
      "Name the variable, coefficient, constant and operations.",
      "Write the rule in words and symbols, including the exponent.",
      "Use the distributive property to explain equivalence for every input.",
    ],
    "Double the reward per action. Test the effect and explain why not every part of the score doubles.",
    { a: 4, b: 3, c: 5, d: 2 },
    "/math/unit-6/projects/version-a/",
  ),
  mission(
    "unit-6-b",
    6,
    "expressions",
    "App Pricing Engine",
    "Create a fictional club-app price model.",
    "Can you explain a price rule so another team can check it?",
    "A transparent price card and expression audit.",
    ["Study planner", "Garden tracker", "Team organizer"],
    [
      "Label each coefficient, term and constant in your model.",
      "Show order of operations for the square term.",
      "Prove the expanded and grouped expressions are equivalent.",
    ],
    "The fixed setup amount changes. Explain which terms change and which remain the same.",
    { a: 3, b: 4, c: 6, d: 3 },
    "/math/unit-6/projects/version-b/",
  ),
  mission(
    "unit-7-a",
    7,
    "coordinates",
    "Theme Park Map Designer",
    "Design a park that visitors can navigate.",
    "Can your map make distance and direction unambiguous?",
    "An accessible map with a route and reflected attraction.",
    ["Nature park", "Science park", "Arts festival"],
    [
      "Plot and label the points on all four quadrants of your paper map.",
      "Use absolute value to explain an axis-aligned distance.",
      "Compare signed coordinates with distances from zero.",
    ],
    "Move the starting attraction across the y-axis. Recalculate distance and explain the reflection.",
    { a: -4, b: 3, c: 6 },
    "/math/unit-7/projects/version-a/",
  ),
  mission(
    "unit-7-b",
    7,
    "coordinates",
    "Submarine Mission Control",
    "Plan a fictional underwater survey.",
    "How can coordinates describe position without confusing depth and distance?",
    "A mission map and signed-number safety briefing.",
    ["Reef survey", "Wreck mapping", "Deep-ocean sampler"],
    [
      "Explain the meaning of negative and positive coordinates.",
      "Show a horizontal route between points with the same depth.",
      "Use opposite points to explain reflection and absolute value.",
    ],
    "Reflect the starting point across the y-axis. Explain what changes about location and route length.",
    { a: -6, b: -4, c: 3 },
    "/math/unit-7/projects/version-b/",
  ),
  mission(
    "unit-8-a",
    8,
    "equations",
    "Escape Room Architect",
    "Build an escape puzzle that can be solved fairly.",
    "Can another team unlock your clue and prove its answer?",
    "Two equation locks, a threshold clue and a solution defense.",
    ["Museum mystery", "Space-station rescue", "Library secret"],
    [
      "Write a story that matches each equation.",
      "Show the inverse operation and substitute to check.",
      "Draw the inequality on a number line and explain its boundary.",
    ],
    "Change the secret value. Rebuild the clues and test that each still has the intended solution.",
    { a: 7, b: 5, c: 4 },
    "/math/unit-8/projects/version-a/",
  ),
  mission(
    "unit-8-b",
    8,
    "equations",
    "Fundraiser Goal Tracker",
    "Plan a fictional club fundraiser.",
    "How can a goal become an equation and a set of possible outcomes?",
    "A goal plan with equations, an inequality and a number line.",
    ["Garden supplies", "Art materials", "Library games"],
    [
      "Define the unknown quantity and its units.",
      "Show how inverse operations solve your progress equations.",
      "Explain why an at-least goal includes the boundary.",
    ],
    "Raise the target. Revise your equation and show one amount that meets the goal and one that does not.",
    { a: 12, b: 8, c: 5 },
    "/math/unit-8/projects/version-b/",
  ),
  mission(
    "unit-8-c",
    8,
    "equations",
    "Master Codebreaker",
    "Create a linked puzzle for a test team.",
    "Will your clues still work when somebody challenges your assumptions?",
    "A puzzle chain, substitution checks and a repaired ambiguous clue.",
    ["Code laboratory", "Time-capsule mystery", "Rescue protocol"],
    [
      "Connect the addition and multiplication locks with the same secret.",
      "Show an inverse-operation solution and a substitution check for each.",
      "Use an inequality gate with several valid outcomes; explain why it is not an equation.",
    ],
    "A tester mistakes “at least” for “greater than.” Use a boundary test to repair the clue.",
    { a: 9, b: 6, c: 7 },
    "/math/unit-8/projects/version-c/",
  ),
  mission(
    "unit-9-a",
    9,
    "relationships",
    "Channel Growth Lab",
    "Model a fictional learning channel.",
    "What can a constant-growth model tell you—and what can’t it?",
    "A table, graph and responsible growth forecast.",
    ["Science explainers", "Art tutorials", "Math puzzles"],
    [
      "Name the independent and dependent variables with units.",
      "Make the table, graph and equation describe the same rule.",
      "Explain the initial value, rate and a limitation of constant growth.",
    ],
    "The growth per week changes. Compare the graphs at the same week and explain the difference.",
    { a: 12, b: 20, c: 6 },
    "/math/unit-9/projects/version-a/",
  ),
  mission(
    "unit-9-b",
    9,
    "relationships",
    "Phone Plan Showdown",
    "Compare fictional club communication plans.",
    "Which plan fits different usage levels?",
    "A consumer guide with equations, tables and a graph.",
    ["Low-use plan", "Team plan", "Event-only plan"],
    [
      "Label the fixed fee and cost per unit of usage.",
      "Graph at least four ordered pairs including zero usage.",
      "Use the same usage amount when comparing two plans.",
    ],
    "Increase the fixed fee but lower the usage rate. Test at two usage levels before recommending a plan.",
    { a: 4, b: 12, c: 8 },
    "/math/unit-9/projects/version-b/",
  ),
  mission(
    "unit-10-a",
    5,
    "solids",
    "Package Design Challenge",
    "Design packaging for a fictional maker kit.",
    "Can your box hold enough while using less material?",
    "A package prototype with a six-face net and efficiency argument.",
    ["Puzzle kit", "Art kit", "Garden kit"],
    [
      "Draw and label all six faces of a closed box net.",
      "Show how fractional edges affect volume.",
      "Compare two boxes and distinguish capacity from material area.",
    ],
    "Change the shape while keeping a similar capacity. Compare material cost before choosing.",
    { a: 5, b: 4, c: 3, d: 2, e: 50 },
    "/math/unit-10/projects/version-a/",
  ),
  mission(
    "unit-10-b",
    5,
    "solids",
    "Aquarium Build Lab",
    "Design a classroom model tank.",
    "How does an open top change the material you need?",
    "A model-tank plan with volume, five-face net and material cost.",
    ["Reef model", "River model", "Research tank"],
    [
      "Draw a five-face net and identify the missing top.",
      "Distinguish model capacity from water actually placed inside.",
      "Explain why surface area and volume use different units.",
    ],
    "Make the tank taller while keeping its floor the same. Compare the change in glass area and capacity.",
    { a: 8, b: 5, c: 4, d: 1.5, e: 150 },
    "/math/unit-10/projects/version-b/",
  ),
  mission(
    "unit-10-c",
    5,
    "solids",
    "3D Geo-Architect",
    "Plan a model research pavilion.",
    "Can fractional dimensions satisfy a capacity target without wasting panels?",
    "A pavilion model, labeled net and design-review defense.",
    ["Field station", "Exhibit pavilion", "Garden lab"],
    [
      "Use fractional edge lengths and show two multiplication steps.",
      "Label paired faces on a net.",
      "Compare volume and panel cost for two possible designs.",
    ],
    "Panel prices rise. Change one dimension, then defend the tradeoff between room and cost.",
    { a: 4.5, b: 3, c: 2.5, d: 10, e: 30 },
    "/math/unit-10/projects/version-c/",
  ),
  mission(
    "statistics-a",
    2,
    "statistics",
    "Maker Club Data Story",
    "Investigate a simulated design trial.",
    "Which story is supported by the data, and which claim goes too far?",
    "A data story with a display, center, variation and limitation.",
    ["Paper tower", "Bridge span", "Prototype test"],
    [
      "State a question that anticipates variation.",
      "Use mean, median and spread to describe the sample.",
      "Support a recommendation with two numbers and one limitation.",
    ],
    "Replace the highest measurement with an outlier. Explain which summary changes most.",
    { data: "3, 5, 5, 7, 9, 13" },
    "/math/statistics/projects/version-a/",
  ),
  mission(
    "statistics-b",
    2,
    "statistics",
    "Community Data Investigation",
    "Advise a fictional community center.",
    "How can a display help people make a fair decision?",
    "An investigation report with an honest display and recommendation.",
    ["Library activity", "Park usage trial", "Maker workshop"],
    [
      "Write a statistical question with units and a population.",
      "Describe shape, center and spread without claiming the sample represents everyone.",
      "Explain how changing an axis could mislead a reader.",
    ],
    "A missing high value is recovered. Recalculate and decide whether your claim needs revision.",
    { data: "8, 10, 10, 12, 14, 18" },
    "/math/statistics/projects/version-b/",
  ),
  mission(
    "world-architect",
    5,
    "solids",
    "World Architect Expedition",
    "Create a model landmark for an exhibition.",
    "How can you turn an ambitious shape into measurable solids?",
    "An exhibit model with a prism net and a geometry explanation.",
    ["Observation tower", "Museum wing", "Community landmark"],
    [
      "Explain that your rectangular prism is a simplified model, not an exact building.",
      "Label dimensions and show both a net and a volume calculation.",
      "Describe what your simplified model leaves out.",
    ],
    "The exhibit gains a height limit. Revise your model and compare capacity with material use.",
    { a: 6, b: 4, c: 7.5, d: 3, e: 150 },
    "/math/unit-10/projects/world-architect/",
  ),
  mission(
    "statistics-life",
    2,
    "statistics",
    "Statistics of Everyday Life",
    "Tell a story with a fictional activity sample.",
    "Does one average describe every observation fairly?",
    "A visual data story; no personal or family information is needed.",
    ["Reading minutes", "Puzzle minutes", "Art minutes"],
    [
      "Label the six simulated observations as practice data.",
      "Explain why values vary and how mean differs from median.",
      "Use a display to challenge an overconfident claim about the average.",
    ],
    "One activity takes much longer. Compare the center and spread before rewriting the headline.",
    { data: "5, 10, 10, 15, 20, 30" },
    "/math/statistics/statistics-of-my-life/",
  ),
  mission(
    "synthesis",
    10,
    "synthesis",
    "Better Block Design Challenge",
    "Pitch a fictional community pop-up.",
    "Can one plan connect space, price and a rule for growth?",
    "A community proposal combining geometry, percents and a two-variable model.",
    ["Reading pop-up", "Community game day", "Garden workshop"],
    [
      "Draw the floor plan and label area units.",
      "Explain the discount as a fraction of the materials subtotal.",
      "Connect an attendance table, graph and cost equation; defend a tradeoff.",
    ],
    "More visitors are expected and materials cost more. Revise the plan and defend it with at least two math ideas.",
    { a: 6, b: 4, c: 5, d: 20, e: 3, f: 12 },
    null,
  ),
];
export const UNIT_NAMES = [
  "Pre-Unit · Division",
  "Math Is Discovery",
  "Statistics",
  "Ratios & Rates",
  "Percents",
  "Area, Surface Area & Volume",
  "Expressions & Number Sense",
  "Integers & the Coordinate Plane",
  "Equations & Inequalities",
  "Two-Variable Relationships",
  "Math Is Synthesis",
];
export const getProject = (id) => PROJECTS.find((p) => p.id === id);
export const studioURL = (id) => `/curriculum/projects/studio/?project=${encodeURIComponent(id)}`;
