name = "shai-school-sync"
main = "../../focus-school/sync-worker/src/sync-room.js"
compatibility_date = "2026-05-25"

[[kv_namespaces]]
binding = "NOAM_SCHOOL_KV"
id = "c6e52c72599447efba23f0646e484974"

[[durable_objects.bindings]]
name = "SYNC_ROOM"
class_name = "SyncRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncRoom"]
