name = "neft-family-meeting-email"
main = "worker.js"
compatibility_date = "2026-05-25"
workers_dev = false

[[send_email]]
name = "FAMILY_MEETING_EMAIL"
destination_address = "jdneft@bcps.k12.md.us"
allowed_sender_addresses = [ "family-connections@eduwonderlab.com" ]
