/**
 * MCAP Review Question Bank — Grade 6 (BCPS Reveal Math, units 1–10).
 *
 * Single source of truth for the 3D Boss Battle. Mirrors the MCAP-aligned bank
 * used by the 2D Review Arcade (math/review-arcade), kept here so the 3D battle
 * is self-contained. Each unit has 8 multiple-choice questions.
 *
 * Question shape: { q, choices[4], answer (index into choices), why, topic }
 * NOTE: the `answer` index points into the ORIGINAL `choices` order. The game
 * shuffles choices at render time and tracks the correct *value*, so this index
 * stays correct no matter how the buttons are ordered on screen.
 */

export const BANK = {
  1: [
    {
      q: "A recipe uses 2 cups of flour for every 3 eggs. What is the ratio of flour to eggs?",
      choices: ["2:3", "3:2", "2:5", "5:2"],
      answer: 0,
      why: "Flour to eggs is 2 to 3, written 2:3.",
      topic: "Ratios",
    },
    {
      q: "There are 12 boys and 8 girls. What is the ratio of girls to boys in simplest form?",
      choices: ["8:12", "2:3", "3:2", "4:6"],
      answer: 1,
      why: "8:12 divides by 4 to give 2:3.",
      topic: "Ratios",
    },
    {
      q: "A car travels 150 miles in 3 hours. What is the unit rate?",
      choices: ["45 mph", "153 mph", "50 mph", "30 mph"],
      answer: 2,
      why: "150 ÷ 3 = 50 miles per hour.",
      topic: "Unit Rate",
    },
    {
      q: "If 4 apples cost $2.00, what is the cost per apple?",
      choices: ["$0.40", "$0.80", "$2.00", "$0.50"],
      answer: 3,
      why: "$2.00 ÷ 4 = $0.50 per apple.",
      topic: "Unit Rate",
    },
    {
      q: "A paint mix uses 5 parts blue to 2 parts white. How much white for 15 parts blue?",
      choices: ["6 parts", "5 parts", "7 parts", "10 parts"],
      answer: 0,
      why: "15 ÷ 5 = 3, so 2 × 3 = 6 parts white.",
      topic: "Ratios",
    },
    {
      q: "Which is the better buy: 6 for $3.00 or 10 for $4.50?",
      choices: ["6 for $3.00", "10 for $4.50", "Same price", "Cannot tell"],
      answer: 1,
      why: "$0.45 each vs $0.50 each — 10 for $4.50 is cheaper per item.",
      topic: "Unit Rate",
    },
    {
      q: "A map scale is 1 inch = 25 miles. How many miles is 4 inches?",
      choices: ["50 miles", "29 miles", "100 miles", "75 miles"],
      answer: 2,
      why: "4 × 25 = 100 miles.",
      topic: "Ratios",
    },
    {
      q: "The ratio of cats to dogs is 3:5. If there are 9 cats, how many dogs?",
      choices: ["12", "11", "18", "15"],
      answer: 3,
      why: "9 ÷ 3 = 3, so 5 × 3 = 15 dogs.",
      topic: "Ratios",
    },
  ],
  2: [
    {
      q: "What is 3/4 ÷ 1/2?",
      choices: ["3/2", "3/8", "2/3", "6/4"],
      answer: 0,
      why: "3/4 × 2/1 = 6/4 = 3/2.",
      topic: "Fraction Division",
    },
    {
      q: "A 6-foot board is cut into 3/4-foot pieces. How many pieces?",
      choices: ["6", "8", "9", "4"],
      answer: 1,
      why: "6 ÷ 3/4 = 6 × 4/3 = 24/3 = 8 pieces.",
      topic: "Fraction Division",
    },
    {
      q: "What is 2/3 ÷ 4?",
      choices: ["8/3", "2/12", "1/6", "6/4"],
      answer: 2,
      why: "2/3 ÷ 4 = 2/3 × 1/4 = 2/12 = 1/6.",
      topic: "Fraction Division",
    },
    {
      q: "How many 1/3-cup servings are in 4 cups?",
      choices: ["7", "4/3", "9", "12"],
      answer: 3,
      why: "4 ÷ 1/3 = 4 × 3 = 12 servings.",
      topic: "Fraction Division",
    },
    {
      q: "What is 5/6 ÷ 2/3?",
      choices: ["5/4", "10/18", "5/9", "4/5"],
      answer: 0,
      why: "5/6 × 3/2 = 15/12 = 5/4.",
      topic: "Fraction Division",
    },
    {
      q: "A pizza is 7/8 left. Each person eats 1/8. How many people can eat?",
      choices: ["8", "7", "6", "5"],
      answer: 1,
      why: "7/8 ÷ 1/8 = 7 people.",
      topic: "Fraction Division",
    },
    {
      q: "What is 9/10 ÷ 3/5?",
      choices: ["27/50", "5/6", "3/2", "9/6"],
      answer: 2,
      why: "9/10 × 5/3 = 45/30 = 3/2.",
      topic: "Fraction Division",
    },
    {
      q: "A ribbon 3/4 yard long is split into 1/8-yard parts. How many parts?",
      choices: ["5", "4", "8", "6"],
      answer: 3,
      why: "3/4 ÷ 1/8 = 3/4 × 8 = 24/4 = 6 parts.",
      topic: "Fraction Division",
    },
  ],
  3: [
    {
      q: "What is 25% of 80?",
      choices: ["20", "25", "40", "16"],
      answer: 0,
      why: "25% = 1/4. 80 ÷ 4 = 20.",
      topic: "Percent",
    },
    {
      q: "15 is what percent of 60?",
      choices: ["15%", "25%", "45%", "20%"],
      answer: 1,
      why: "15/60 = 1/4 = 25%.",
      topic: "Percent",
    },
    {
      q: "A $40 shirt is 30% off. What is the discount amount?",
      choices: ["$10", "$30", "$12", "$28"],
      answer: 2,
      why: "30% of $40 = 0.30 × 40 = $12.",
      topic: "Percent",
    },
    {
      q: "What is 110% of 50?",
      choices: ["60", "50", "11", "55"],
      answer: 3,
      why: "110% = 1.10. 1.10 × 50 = 55.",
      topic: "Percent",
    },
    {
      q: "If 20% of a number is 16, what is the number?",
      choices: ["80", "32", "36", "3.2"],
      answer: 0,
      why: "16 ÷ 0.20 = 80.",
      topic: "Percent",
    },
    {
      q: "A class of 25 has 60% girls. How many girls?",
      choices: ["10", "15", "12", "60"],
      answer: 1,
      why: "60% of 25 = 0.60 × 25 = 15.",
      topic: "Percent",
    },
    {
      q: "Convert 3/5 to a percent.",
      choices: ["35%", "53%", "60%", "65%"],
      answer: 2,
      why: "3 ÷ 5 = 0.60 = 60%.",
      topic: "Percent",
    },
    {
      q: "A phone costs $200 plus 8% tax. What is the total?",
      choices: ["$208", "$224", "$240", "$216"],
      answer: 3,
      why: "8% of 200 = $16. 200 + 16 = $216.",
      topic: "Percent",
    },
  ],
  4: [
    {
      q: "What is the GCF of 24 and 36?",
      choices: ["12", "6", "8", "18"],
      answer: 0,
      why: "12 is the greatest factor shared by 24 and 36.",
      topic: "GCF/LCM",
    },
    {
      q: "What is the LCM of 4 and 6?",
      choices: ["24", "12", "10", "6"],
      answer: 1,
      why: "Multiples of 6: 6,12; of 4: 4,8,12. LCM = 12.",
      topic: "GCF/LCM",
    },
    {
      q: "What is 0.45 + 0.7?",
      choices: ["0.52", "1.05", "1.15", "0.115"],
      answer: 2,
      why: "Line up decimals: 0.45 + 0.70 = 1.15.",
      topic: "Decimals",
    },
    {
      q: "What is 6.4 × 0.5?",
      choices: ["32", "3.0", "0.32", "3.2"],
      answer: 3,
      why: "6.4 × 0.5 = 3.2 (half of 6.4).",
      topic: "Decimals",
    },
    {
      q: "What is 7.2 ÷ 0.8?",
      choices: ["9", "0.9", "90", "8"],
      answer: 0,
      why: "7.2 ÷ 0.8 = 72 ÷ 8 = 9.",
      topic: "Decimals",
    },
    {
      q: "Which shows the prime factorization of 60?",
      choices: ["2 × 3 × 5", "2² × 3 × 5", "2² × 15", "4 × 15"],
      answer: 1,
      why: "60 = 4 × 15 = 2² × 3 × 5.",
      topic: "Factors",
    },
    {
      q: "What is the GCF of 18 and 30?",
      choices: ["3", "9", "6", "15"],
      answer: 2,
      why: "Shared factors of 18 and 30: 6 is greatest.",
      topic: "GCF/LCM",
    },
    {
      q: "A bus comes every 12 min, another every 8 min. When do both arrive together?",
      choices: ["20 min", "16 min", "48 min", "24 min"],
      answer: 3,
      why: "LCM of 12 and 8 = 24 minutes.",
      topic: "GCF/LCM",
    },
  ],
  5: [
    {
      q: "What is the area of a triangle with base 10 and height 6?",
      choices: ["30", "60", "16", "30.5"],
      answer: 0,
      why: "Area = ½ × base × height = ½ × 10 × 6 = 30.",
      topic: "Area",
    },
    {
      q: "A rectangle is 8 by 5. What is its area?",
      choices: ["26", "40", "13", "45"],
      answer: 1,
      why: "Area = length × width = 8 × 5 = 40.",
      topic: "Area",
    },
    {
      q: "What is the area of a parallelogram with base 12 and height 4?",
      choices: ["32", "16", "48", "24"],
      answer: 2,
      why: "Area = base × height = 12 × 4 = 48.",
      topic: "Area",
    },
    {
      q: "A trapezoid has bases 6 and 10, height 4. What is its area?",
      choices: ["60", "40", "16", "32"],
      answer: 3,
      why: "Area = ½(b₁+b₂)h = ½(16)(4) = 32.",
      topic: "Area",
    },
    {
      q: "A square has area 49. What is its side length?",
      choices: ["7", "14", "24.5", "12"],
      answer: 0,
      why: "√49 = 7, so each side is 7.",
      topic: "Area",
    },
    {
      q: "What is the area of a triangle with base 9 and height 8?",
      choices: ["72", "36", "17", "45"],
      answer: 1,
      why: "½ × 9 × 8 = 36.",
      topic: "Area",
    },
    {
      q: "A composite shape = rectangle (6×4) + square (4×4). Total area?",
      choices: ["24", "16", "40", "32"],
      answer: 2,
      why: "24 + 16 = 40 square units.",
      topic: "Area",
    },
    {
      q: "Find the area of a triangle with base 5 and height 12.",
      choices: ["60", "17", "25", "30"],
      answer: 3,
      why: "½ × 5 × 12 = 30.",
      topic: "Area",
    },
  ],
  6: [
    {
      q: "Simplify: 3(x + 4)",
      choices: ["3x + 12", "3x + 4", "x + 12", "7x"],
      answer: 0,
      why: "Distribute: 3·x + 3·4 = 3x + 12.",
      topic: "Expressions",
    },
    {
      q: "Evaluate 2x + 5 when x = 6.",
      choices: ["13", "17", "23", "11"],
      answer: 1,
      why: "2(6) + 5 = 12 + 5 = 17.",
      topic: "Expressions",
    },
    {
      q: "Write '5 less than a number n' as an expression.",
      choices: ["5 − n", "5n", "n − 5", "n + 5"],
      answer: 2,
      why: "'5 less than n' means n − 5.",
      topic: "Expressions",
    },
    {
      q: "Combine like terms: 4x + 3x − 2",
      choices: ["9x", "7x + 2", "5x", "7x − 2"],
      answer: 3,
      why: "4x + 3x = 7x, so 7x − 2.",
      topic: "Expressions",
    },
    {
      q: "What is the value of 6² − 10?",
      choices: ["26", "16", "32", "46"],
      answer: 0,
      why: "6² = 36. 36 − 10 = 26.",
      topic: "Exponents",
    },
    {
      q: "Which expression equals 6x − 15?",
      choices: ["3(2x + 5)", "3(2x − 5)", "6(x − 15)", "3(2x − 15)"],
      answer: 1,
      why: "3(2x − 5) = 6x − 15.",
      topic: "Expressions",
    },
    {
      q: "Evaluate (4 + 3)² ÷ 7.",
      choices: ["5", "49", "7", "14"],
      answer: 2,
      why: "(4+3)² = 49. 49 ÷ 7 = 7.",
      topic: "Exponents",
    },
    {
      q: "Solve for x: x + 8 = 20",
      choices: ["28", "8", "160", "12"],
      answer: 3,
      why: "x = 20 − 8 = 12.",
      topic: "Equations",
    },
  ],
  7: [
    {
      q: "What is the absolute value of −15?",
      choices: ["15", "−15", "1/15", "0"],
      answer: 0,
      why: "|−15| = 15, the distance from 0.",
      topic: "Integers",
    },
    {
      q: "Order from least to greatest: −3, 5, −8, 0",
      choices: ["−3, −8, 0, 5", "−8, −3, 0, 5", "0, −3, 5, −8", "5, 0, −3, −8"],
      answer: 1,
      why: "From least: −8, −3, 0, 5.",
      topic: "Integers",
    },
    {
      q: "Which is greater: −7 or −2?",
      choices: ["−7", "Equal", "−2", "Cannot tell"],
      answer: 2,
      why: "−2 is to the right of −7 on the number line, so −2 > −7.",
      topic: "Integers",
    },
    {
      q: "A diver is at −30 ft and descends 12 ft. What is the new depth?",
      choices: ["−18 ft", "42 ft", "−360 ft", "−42 ft"],
      answer: 3,
      why: "−30 − 12 = −42 ft.",
      topic: "Integers",
    },
    {
      q: "What is the opposite of −9?",
      choices: ["9", "−9", "0", "1/9"],
      answer: 0,
      why: "The opposite of −9 is 9.",
      topic: "Integers",
    },
    {
      q: "Which point is farther from 0: −9 or 6?",
      choices: ["6", "−9", "Same", "Cannot tell"],
      answer: 1,
      why: "|−9| = 9 > |6| = 6, so −9 is farther.",
      topic: "Absolute Value",
    },
    {
      q: "On a coordinate plane, point (−4, 3) is in which quadrant?",
      choices: ["Quadrant I", "Quadrant III", "Quadrant II", "Quadrant IV"],
      answer: 2,
      why: "Negative x, positive y → Quadrant II.",
      topic: "Coordinates",
    },
    {
      q: "What is |−3| + |4|?",
      choices: ["1", "−7", "12", "7"],
      answer: 3,
      why: "|−3| = 3, |4| = 4, 3 + 4 = 7.",
      topic: "Absolute Value",
    },
  ],
  8: [
    {
      q: "What is the mean of 4, 8, 6, 2?",
      choices: ["5", "6", "4", "20"],
      answer: 0,
      why: "(4+8+6+2)/4 = 20/4 = 5.",
      topic: "Statistics",
    },
    {
      q: "What is the median of 3, 7, 9, 5, 1?",
      choices: ["7", "5", "9", "3"],
      answer: 1,
      why: "Sorted: 1,3,5,7,9. Middle = 5.",
      topic: "Statistics",
    },
    {
      q: "What is the mode of 2, 3, 3, 5, 7, 3?",
      choices: ["5", "2", "3", "7"],
      answer: 2,
      why: "3 appears most often (three times).",
      topic: "Statistics",
    },
    {
      q: "What is the range of 12, 5, 8, 20, 3?",
      choices: ["15", "20", "8", "17"],
      answer: 3,
      why: "Range = 20 − 3 = 17.",
      topic: "Statistics",
    },
    {
      q: "Which is a statistical question?",
      choices: ["How tall are students in my class?", "How tall am I?", "What is 2+2?", "What color is the sky?"],
      answer: 0,
      why: "A statistical question has variety in answers across a group.",
      topic: "Statistics",
    },
    {
      q: "The median splits data into what?",
      choices: ["Three parts", "Two equal halves", "The average", "The mode"],
      answer: 1,
      why: "Median is the middle value, splitting data in half.",
      topic: "Statistics",
    },
    {
      q: "What is the mean of 10, 10, 20?",
      choices: ["10", "20", "13.3", "40"],
      answer: 2,
      why: "(10+10+20)/3 = 40/3 ≈ 13.3.",
      topic: "Statistics",
    },
    {
      q: "In a dot plot, what does a tall stack of dots mean?",
      choices: ["That value is rare", "An error", "The mean", "That value occurs often"],
      answer: 3,
      why: "More dots = higher frequency for that value.",
      topic: "Data Displays",
    },
  ],
  9: [
    {
      q: "What are the coordinates of a point 3 right and 2 up from the origin?",
      choices: ["(3, 2)", "(2, 3)", "(−3, 2)", "(3, −2)"],
      answer: 0,
      why: "Right = +x, up = +y, so (3, 2).",
      topic: "Coordinates",
    },
    {
      q: "Reflect (4, 5) over the x-axis. What is the image?",
      choices: ["(−4, 5)", "(4, −5)", "(−4, −5)", "(5, 4)"],
      answer: 1,
      why: "Reflecting over x-axis negates y: (4, −5).",
      topic: "Reflections",
    },
    {
      q: "What is the distance between (2, 3) and (2, 8)?",
      choices: ["6", "11", "5", "10"],
      answer: 2,
      why: "Same x, so distance = |8 − 3| = 5.",
      topic: "Distance",
    },
    {
      q: "Which quadrant contains (−5, −2)?",
      choices: ["Quadrant II", "Quadrant IV", "Quadrant I", "Quadrant III"],
      answer: 3,
      why: "Both negative → Quadrant III.",
      topic: "Coordinates",
    },
    {
      q: "The point (0, −6) lies on which axis?",
      choices: ["y-axis", "x-axis", "Both", "Neither"],
      answer: 0,
      why: "x = 0 means it's on the y-axis.",
      topic: "Coordinates",
    },
    {
      q: "Reflect (−3, 7) over the y-axis. What is the image?",
      choices: ["(−3, −7)", "(3, 7)", "(3, −7)", "(7, −3)"],
      answer: 1,
      why: "Reflecting over y-axis negates x: (3, 7).",
      topic: "Reflections",
    },
    {
      q: "Perimeter of a rectangle with corners (0,0),(4,0),(4,3),(0,3)?",
      choices: ["12", "7", "14", "24"],
      answer: 2,
      why: "Sides 4 and 3: P = 2(4+3) = 14.",
      topic: "Distance",
    },
    {
      q: "Distance from (−3, 0) to (5, 0)?",
      choices: ["2", "15", "−8", "8"],
      answer: 3,
      why: "|5 − (−3)| = 8.",
      topic: "Distance",
    },
  ],
  10: [
    {
      q: "What is the volume of a box 3 × 4 × 5?",
      choices: ["60", "12", "47", "120"],
      answer: 0,
      why: "V = l × w × h = 3 × 4 × 5 = 60.",
      topic: "Volume",
    },
    {
      q: "A cube has edge length 4. What is its volume?",
      choices: ["16", "64", "12", "48"],
      answer: 1,
      why: "V = 4³ = 64.",
      topic: "Volume",
    },
    {
      q: "A right rectangular prism is 2½ × 4 × 3. What is the volume?",
      choices: ["25", "9.5", "30", "60"],
      answer: 2,
      why: "2.5 × 4 × 3 = 30 cubic units.",
      topic: "Volume",
    },
    {
      q: "How many unit cubes fill a 2 × 3 × 2 box?",
      choices: ["7", "10", "14", "12"],
      answer: 3,
      why: "2 × 3 × 2 = 12 unit cubes.",
      topic: "Volume",
    },
    {
      q: "A box has volume 24 and base area 6. What is its height?",
      choices: ["4", "6", "144", "18"],
      answer: 0,
      why: "Height = Volume ÷ base = 24 ÷ 6 = 4.",
      topic: "Volume",
    },
    {
      q: "What is the volume of a 1 × 1 × 1 cube?",
      choices: ["3", "1", "0", "6"],
      answer: 1,
      why: "1 × 1 × 1 = 1 cubic unit.",
      topic: "Volume",
    },
    {
      q: "A fish tank is 10 × 5 × 4. What is its volume?",
      choices: ["76", "120", "200", "19"],
      answer: 2,
      why: "10 × 5 × 4 = 200 cubic units.",
      topic: "Volume",
    },
    {
      q: "Find the volume of a cube with edge 5.",
      choices: ["15", "25", "75", "125"],
      answer: 3,
      why: "5³ = 125.",
      topic: "Volume",
    },
  ],
};

/**
 * Per-unit metadata: the boss "phase" for each unit, MCAP standard, theme color.
 * Phases are ordered 1→10 so difficulty climbs with the curriculum.
 */
export const UNITS = [
  {
    u: 1,
    standard: "6.RP.A.1–3",
    theme: "Ratios & Unit Rates",
    title: "Ratio Wraith",
    color: 0x1fa6a2,
  },
  {
    u: 2,
    standard: "6.NS.A.1",
    theme: "Dividing Fractions",
    title: "Fraction Phantom",
    color: 0xe07b53,
  },
  {
    u: 3,
    standard: "6.RP.A.2–3",
    theme: "Percents & Rates",
    title: "Percent Prowler",
    color: 0xf2c15b,
  },
  {
    u: 4,
    standard: "6.NS.B.2–4",
    theme: "Decimals, GCF & LCM",
    title: "Factor Fiend",
    color: 0x7c5cff,
  },
  {
    u: 5,
    standard: "6.G.A.1",
    theme: "Area of Polygons",
    title: "Area Aberration",
    color: 0x49c06a,
  },
  {
    u: 6,
    standard: "6.EE.A.1–4",
    theme: "Expressions & Exponents",
    title: "Expression Engine",
    color: 0xff6f9c,
  },
  {
    u: 7,
    standard: "6.NS.C.5–7",
    theme: "Integers & Absolute Value",
    title: "Integer Leviathan",
    color: 0x2f7fff,
  },
  {
    u: 8,
    standard: "6.SP.A–B",
    theme: "Statistics & Data",
    title: "Data Specter",
    color: 0x36c5d6,
  },
  {
    u: 9,
    standard: "6.NS.C.6, 8",
    theme: "The Coordinate Plane",
    title: "Quadrant Quaker",
    color: 0xc77dff,
  },
  {
    u: 10,
    standard: "6.G.A.2",
    theme: "Volume of Prisms",
    title: "Volume Vault Golem",
    color: 0xffa94d,
  },
];

/** All units 1..10 as a flat list, validated for shape. */
export function allUnits() {
  return UNITS.map((m) => m.u);
}
