// Generate the browser artifact `assets/games2d-data.js` from the canonical
// Node source of truth `scripts/games2d/data.mjs`.
//
// The 2D/Phaser math games are standalone static HTML pages, so they read the
// shared standards/vocab/misconception/tier data at runtime from the global
// `window.Games2DData` that this artifact installs. Edit `data.mjs`, then run:
//
//     npm run generate-games2d-data
//
// Idempotent: re-running with no data change rewrites byte-identical output.
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { GAMES_2D } from "./data.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "assets", "games2d-data.js");

const banner =
  "/* AUTO-GENERATED by scripts/games2d/generate.mjs — DO NOT EDIT BY HAND.\n" +
  " * Source of truth: scripts/games2d/data.mjs\n" +
  " * Regenerate: npm run generate-games2d-data */\n";

const body =
  "window.Games2DData = " + JSON.stringify(GAMES_2D, null, 2) + ";\n";

writeFileSync(OUT, banner + body);

const ids = Object.keys(GAMES_2D);
console.log(`games2d-data: wrote ${OUT}`);
console.log(`  games: ${ids.length} (${ids.join(", ")})`);
