// Generated by scripts/generate-curriculum-context.mjs; edit the lesson configs.
window.LESSON_PROJECTS = {
  "1-1": [],
  "1-2": [],
  "1-3": [],
  "1-4": [],
  "1-5": [],
  "1-6": [],
  "2-1": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "📊 Statistics of My Life",
      "href": "/math/statistics/statistics-of-my-life/"
    },
    {
      "text": "🔎 Statistical Questions Data Lab",
      "href": "/math/statistics/6-sp-a-1data-lab-6-sp-a-1-flagship/"
    },
    {
      "text": "🎮 Statistical Questions Game",
      "href": "/math/statistics/6-sp-a-1game/"
    }
  ],
  "2-2": [
    {
      "text": "🏀 Histogram Master Lab",
      "href": "/math/statistics/histogram-master-lab/"
    }
  ],
  "2-3": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "📐 Mean, Median & Mode Intro",
      "href": "/math/statistics/mean-median-mode-intro/"
    },
    {
      "text": "🎮 Mean, Median & Mode Game",
      "href": "/math/statistics/mean-median-mode-game/"
    },
    {
      "text": "⚽ Soccer & Bracelets Center Lab",
      "href": "/math/statistics/meanmedianmodesoccerandbracelets/"
    }
  ],
  "2-4": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "📦 Box Plot Builder",
      "href": "/math/statistics/box-plot-builder/"
    },
    {
      "text": "🕵️ Box Plot Detective",
      "href": "/math/statistics/box-plot-detective/"
    }
  ],
  "2-5": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "🕵️ Distribution Detective",
      "href": "/math/statistics/distribution-detective/"
    },
    {
      "text": "📊 Histogram Master Lab",
      "href": "/math/statistics/histogram-master-lab/"
    },
    {
      "text": "📖 Unit 8 Graphic Novel",
      "href": "/graphic-novels/unit8/graphic-novel-1.html"
    }
  ],
  "2-6": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "☄️ Asteroid Miner — Multi-Digit Division",
      "href": "/math/unit-1/6-ns-b-2game/"
    },
    {
      "text": "🔬 Division Mastery",
      "href": "/math/unit-1/6-ns-b-2reviewactivities/"
    }
  ],
  "2-7": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🍳 Cooking Simulator — Decimal Operations",
      "href": "/math/unit-1/6-ns-b-3game/"
    },
    {
      "text": "📖 Decimal Division Drive (Part 1)",
      "href": "/graphic-novels/lessons/u1-l7/graphic-novel-1.html"
    }
  ],
  "2-8": [],
  "2-9": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "📈 Data Studio Master",
      "href": "/neft-data-studio/"
    },
    {
      "text": "🕵️ Distribution Detective",
      "href": "/math/statistics/distribution-detective/"
    }
  ],
  "2-10": [
    {
      "text": "🏆 Project — Statistics in Action",
      "href": "/math/statistics/projects/"
    },
    {
      "text": "🕵️ Distribution Detective",
      "href": "/math/statistics/distribution-detective/"
    },
    {
      "text": "📈 Data Studio Master",
      "href": "/neft-data-studio/"
    }
  ],
  "2-11": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🍳 Cooking Simulator — Decimal Operations",
      "href": "/math/unit-1/6-ns-b-3game/"
    },
    {
      "text": "📖 Decimal Docking Bay (Part 1)",
      "href": "/graphic-novels/lessons/u1-l5l6/graphic-novel-1.html"
    }
  ],
  "2-12": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🍳 Cooking Simulator — Decimal Operations",
      "href": "/math/unit-1/6-ns-b-3game/"
    },
    {
      "text": "📖 Decimal Docking Bay (Part 2)",
      "href": "/graphic-novels/lessons/u1-l5l6/graphic-novel-2.html"
    }
  ],
  "3-1": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "🍳 Ratio Lab",
      "href": "/math/unit-3/ratio-lab/index.html"
    },
    {
      "text": "🎮 Ratio Concept Game (6.AT.1)",
      "href": "/math/unit-3/6-rp-1game/index.html"
    },
    {
      "text": "📖 Unit 3 Graphic Novel",
      "href": "/graphic-novels/unit3/graphic-novel-1.html"
    }
  ],
  "3-2": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🕹️ RatioLab — Unit Rate Playground",
      "href": "/ratiolab/index.html"
    },
    {
      "text": "🛒 Supermarket Unit Rate Duel",
      "href": "/math/unit-4/unit-rate-duel/index.html"
    },
    {
      "text": "📖 Graphic Novel — Shopping Mall Mogul",
      "href": "/graphic-novels/unit4/graphic-novel-1.html"
    }
  ],
  "3-3": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "🏭 Recipe Factory Line",
      "href": "/math/unit-3/recipe-factory-line/index.html"
    },
    {
      "text": "🎮 Ratio Tables Game (6.AT.3a)",
      "href": "/math/unit-4/6-rp-a-3game/index.html"
    }
  ],
  "3-4": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "🏭 Recipe Factory Line",
      "href": "/math/unit-3/recipe-factory-line/index.html"
    },
    {
      "text": "🎮 Ratio Tables Game (6.AT.3a)",
      "href": "/math/unit-4/6-rp-a-3game/index.html"
    }
  ],
  "3-5": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "⚔️ Unit Rate Duel",
      "href": "/math/unit-4/unit-rate-duel/index.html"
    },
    {
      "text": "🏁 Ratio Rally",
      "href": "/math/unit-3/games/unit3-ratio-rally.html"
    }
  ],
  "3-6": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "⚔️ Unit Rate Duel",
      "href": "/math/unit-4/unit-rate-duel/index.html"
    },
    {
      "text": "🎮 Ratio Reasoning Game (6.AT.3)",
      "href": "/math/unit-4/6-rp-a-3game/index.html"
    }
  ],
  "3-7": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "🏁 Ratio Rally",
      "href": "/math/unit-3/games/unit3-ratio-rally.html"
    },
    {
      "text": "⚔️ Unit Rate Duel",
      "href": "/math/unit-4/unit-rate-duel/index.html"
    },
    {
      "text": "📖 Unit 3 Graphic Novel",
      "href": "/graphic-novels/unit3/graphic-novel-2.html"
    }
  ],
  "3-8": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🕹️ RatioLab — Unit Rate Playground",
      "href": "/ratiolab/index.html"
    },
    {
      "text": "🛒 Supermarket Unit Rate Duel",
      "href": "/math/unit-4/unit-rate-duel/index.html"
    }
  ],
  "3-9": [
    {
      "text": "🏆 Project — Ratios in Action",
      "href": "/math/unit-3/projects/"
    },
    {
      "text": "⛽ Ratio Fuel Mixer",
      "href": "/math/unit-3/ratio-fuel-mixer/index.html"
    },
    {
      "text": "🍳 Ratio Lab",
      "href": "/math/unit-3/ratio-lab/index.html"
    },
    {
      "text": "📖 Unit 3 Graphic Novel",
      "href": "/graphic-novels/unit3/graphic-novel-2.html"
    }
  ],
  "3-10": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "⛽ Ratio Table Fuel Mixer",
      "href": "/math/unit-3/ratio-fuel-mixer/index.html"
    },
    {
      "text": "🍳 Recipe Factory — Scale the Ratio",
      "href": "/math/unit-3/recipe-factory-line/index.html"
    }
  ],
  "4-1": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🎯 Percent Shadow-Caster",
      "href": "/math/unit-4/percent-shadow-caster/index.html"
    },
    {
      "text": "📖 Graphic Novel — Shopping Mall Mogul (Part 2)",
      "href": "/graphic-novels/unit4/graphic-novel-2.html"
    }
  ],
  "4-2": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🎯 Percent Shadow-Caster",
      "href": "/math/unit-4/percent-shadow-caster/index.html"
    },
    {
      "text": "📐 Ratios & Proportions Study Guide",
      "href": "/math/unit-4/6-rp-a-2-interactive-study-guide/index.html"
    }
  ],
  "4-3": [],
  "4-4": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🎯 Percent Shadow-Caster",
      "href": "/math/unit-4/percent-shadow-caster/index.html"
    },
    {
      "text": "🏷️ Discount Dash",
      "href": "/math/unit-4/games/unit4-discount-dash.html"
    }
  ],
  "4-5": [
    {
      "text": "🏆 Project — Rates & Percents in Action",
      "href": "/math/unit-4/projects/"
    },
    {
      "text": "🏷️ Discount Dash",
      "href": "/math/unit-4/games/unit4-discount-dash.html"
    },
    {
      "text": "📖 Graphic Novel — Shopping Mall Mogul",
      "href": "/graphic-novels/unit4/graphic-novel-1.html"
    }
  ],
  "5-1": [
    {
      "text": "🏆 Project — Area in Action",
      "href": "/math/unit-5/projects/"
    },
    {
      "text": "🏙️ Area Architect — City Builder",
      "href": "/math/unit-5/games/unit5-area-architect.html"
    },
    {
      "text": "🎢 Graphic Novel #1 — Theme Park Engineer",
      "href": "/graphic-novels/unit5/graphic-novel-1.html"
    }
  ],
  "5-2": [
    {
      "text": "🏆 Project — Area in Action",
      "href": "/math/unit-5/projects/"
    },
    {
      "text": "🏙️ Area Architect — City Builder",
      "href": "/math/unit-5/games/unit5-area-architect.html"
    },
    {
      "text": "🎢 Graphic Novel #2 — Theme Park Engineer",
      "href": "/graphic-novels/unit5/graphic-novel-2.html"
    }
  ],
  "5-3": [
    {
      "text": "🏆 Project — Area in Action",
      "href": "/math/unit-5/projects/"
    },
    {
      "text": "🏙️ Area Architect — City Builder",
      "href": "/math/unit-5/games/unit5-area-architect.html"
    },
    {
      "text": "🎢 Graphic Novel #1 — Theme Park Engineer",
      "href": "/graphic-novels/unit5/graphic-novel-1.html"
    }
  ],
  "5-4": [
    {
      "text": "🏆 Project — Area in Action",
      "href": "/math/unit-5/projects/"
    },
    {
      "text": "🛠️ Geometry Prep Studio",
      "href": "/geometry-prep/"
    },
    {
      "text": "🌍 World Architect Geometry Challenge",
      "href": "/world-architect-math-project/"
    },
    {
      "text": "🎢 Graphic Novel #2 — Theme Park Engineer",
      "href": "/graphic-novels/unit5/graphic-novel-2.html"
    }
  ],
  "5-5": [
    {
      "text": "📦 NetFold Pro 3D Simulator",
      "href": "/netfold-pro/"
    },
    {
      "text": "🏆 Project — Volume & Surface Area in Action",
      "href": "/math/unit-10/projects/"
    },
    {
      "text": "📦 Volume Vault",
      "href": "/math/unit-10/games/unit10-volume-vault.html"
    },
    {
      "text": "🧊 3D Volume Builder",
      "href": "/games/3d/unit-10/"
    },
    {
      "text": "📐 Surface Area Packer",
      "href": "/geometry-prep/surface-area-packer/"
    }
  ],
  "5-6": [
    {
      "text": "🏆 Project — Volume & Surface Area in Action",
      "href": "/math/unit-10/projects/"
    },
    {
      "text": "📝 Surface Area Review",
      "href": "/surface-area-review/"
    },
    {
      "text": "📐 Surface Area Packer",
      "href": "/geometry-prep/surface-area-packer/"
    },
    {
      "text": "📖 Unit 10 Graphic Novel — Part 1",
      "href": "/graphic-novels/unit10/graphic-novel-1.html"
    }
  ],
  "5-7": [
    {
      "text": "🏆 Project — Volume & Surface Area in Action",
      "href": "/math/unit-10/projects/"
    },
    {
      "text": "📝 Surface Area Review",
      "href": "/surface-area-review/"
    },
    {
      "text": "📐 Surface Area Packer",
      "href": "/geometry-prep/surface-area-packer/"
    },
    {
      "text": "📖 Unit 10 Graphic Novel — Part 2",
      "href": "/graphic-novels/unit10/graphic-novel-2.html"
    }
  ],
  "5-8": [
    {
      "text": "🏆 Project — Volume & Surface Area in Action",
      "href": "/math/unit-10/projects/"
    },
    {
      "text": "📝 Surface Area Review",
      "href": "/surface-area-review/"
    },
    {
      "text": "🧩 Tangram Architect",
      "href": "/geometry-prep/tangram-architect/"
    },
    {
      "text": "📖 Unit 10 Graphic Novel — Part 2",
      "href": "/graphic-novels/unit10/graphic-novel-2.html"
    }
  ],
  "5-9": [
    {
      "text": "🏆 Project — Area in Action",
      "href": "/math/unit-5/projects/"
    },
    {
      "text": "🧩 Tangram Polygon Architect",
      "href": "/geometry-prep/tangram-architect/"
    },
    {
      "text": "📐 Coordinate Polygon Architect",
      "href": "/geometry-prep/coordinate-polygon-architect/"
    },
    {
      "text": "🏙️ Area Architect — City Builder",
      "href": "/math/unit-5/games/unit5-area-architect.html"
    }
  ],
  "5-10": [
    {
      "text": "🏆 Project — Volume & Surface Area in Action",
      "href": "/math/unit-10/projects/"
    },
    {
      "text": "📦 Volume Vault",
      "href": "/math/unit-10/games/unit10-volume-vault.html"
    },
    {
      "text": "🏗️ World Architect Math Project",
      "href": "/world-architect-math-project/"
    },
    {
      "text": "📐 Surface Area Packer",
      "href": "/geometry-prep/surface-area-packer/"
    }
  ],
  "6-1": [
    {
      "text": "🏆 Project — Fraction Division in Action",
      "href": "/math/unit-2/projects/"
    },
    {
      "text": "⚽ Fractions Soccer",
      "href": "/fractions-soccer/"
    },
    {
      "text": "📖 Master Chef Kitchen — Recipe Rescue (Part 1)",
      "href": "/graphic-novels/unit2/graphic-novel-1.html"
    }
  ],
  "6-2": [
    {
      "text": "🏆 Project — Fraction Division in Action",
      "href": "/math/unit-2/projects/"
    },
    {
      "text": "⚽ Fraction Division Soccer",
      "href": "/math/unit-2/fraction-division-soccer/"
    },
    {
      "text": "🍳 Fraction Kitchen",
      "href": "/math/unit-2/games/unit2-fraction-kitchen.html"
    },
    {
      "text": "📖 Master Chef Kitchen — Recipe Rescue (Part 1)",
      "href": "/graphic-novels/unit2/graphic-novel-1.html"
    }
  ],
  "6-3": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "🎮 Expression Engine",
      "href": "/math/unit-6/games/unit6-expression-engine.html"
    }
  ],
  "6-4": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "🎮 Expression Engine",
      "href": "/math/unit-6/games/unit6-expression-engine.html"
    }
  ],
  "6-5": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "✍️ Word-to-Equations",
      "href": "/word-to-equations/"
    }
  ],
  "6-6": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "🔥 Equivalent Expressions Forge",
      "href": "/math/unit-6/equivalent-expressions-forge/"
    },
    {
      "text": "🎮 Expression Engine",
      "href": "/math/unit-6/games/unit6-expression-engine.html"
    }
  ],
  "6-7": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🪙 Treasure Hunter — GCF & LCM",
      "href": "/math/unit-1/6-ns-b-4game/"
    },
    {
      "text": "🔬 Factor & Multiple Review Lab",
      "href": "/math/unit-1/6-ns-b-4review/"
    },
    {
      "text": "📖 Prime Station: The Factor Code (Part 2)",
      "href": "/graphic-novels/unit1/graphic-novel-2.html"
    }
  ],
  "6-8": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "⚗️ Distributive Alchemy",
      "href": "/math/unit-6/distributive-alchemy/"
    },
    {
      "text": "🔥 Equivalent Expressions Forge",
      "href": "/math/unit-6/equivalent-expressions-forge/"
    }
  ],
  "6-9": [
    {
      "text": "🏆 Project — Fraction Division in Action",
      "href": "/math/unit-2/projects/"
    },
    {
      "text": "⚽ Fraction Division Soccer",
      "href": "/math/unit-2/fraction-division-soccer/"
    },
    {
      "text": "📖 Master Chef Kitchen — Recipe Rescue (Part 2)",
      "href": "/graphic-novels/unit2/graphic-novel-2.html"
    }
  ],
  "6-10": [
    {
      "text": "🏆 Project — Fraction Division in Action",
      "href": "/math/unit-2/projects/"
    },
    {
      "text": "🍳 Fraction Kitchen",
      "href": "/math/unit-2/games/unit2-fraction-kitchen.html"
    },
    {
      "text": "📖 Master Chef Kitchen — Recipe Rescue (Part 2)",
      "href": "/graphic-novels/unit2/graphic-novel-2.html"
    }
  ],
  "6-11": [
    {
      "text": "🏆 Project — Fraction Division in Action",
      "href": "/math/unit-2/projects/"
    },
    {
      "text": "⚽ Fractions Soccer",
      "href": "/fractions-soccer/"
    },
    {
      "text": "🍳 Fraction Kitchen",
      "href": "/math/unit-2/games/unit2-fraction-kitchen.html"
    }
  ],
  "6-12": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🪙 Treasure Hunter — GCF & LCM",
      "href": "/math/unit-1/6-ns-b-4game/"
    },
    {
      "text": "🔬 Factor & Multiple Review Lab",
      "href": "/math/unit-1/6-ns-b-4review/"
    },
    {
      "text": "📖 Prime Station: The Factor Code (Part 1)",
      "href": "/graphic-novels/unit1/graphic-novel-1.html"
    }
  ],
  "6-13": [
    {
      "text": "🏆 Project — Number System in Action",
      "href": "/math/unit-1/projects/"
    },
    {
      "text": "🌳 Factor Tree Space Salvage",
      "href": "/math/unit-1/factor-tree-salvage/"
    },
    {
      "text": "🧱 Factor Frenzy — Brick Breaker",
      "href": "/math/unit-1/games/unit1-factor-frenzy.html"
    },
    {
      "text": "📖 Prime Station: The Factor Code (Part 1)",
      "href": "/graphic-novels/unit1/graphic-novel-1.html"
    }
  ],
  "6-14": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "⚗️ Distributive Alchemy",
      "href": "/math/unit-6/distributive-alchemy/"
    },
    {
      "text": "🎮 Expression Engine",
      "href": "/math/unit-6/games/unit6-expression-engine.html"
    }
  ],
  "6-15": [
    {
      "text": "🏆 Project — Expressions in Action",
      "href": "/math/unit-6/projects/"
    },
    {
      "text": "🔥 Equivalent Expressions Forge",
      "href": "/math/unit-6/equivalent-expressions-forge/"
    },
    {
      "text": "⚗️ Distributive Alchemy",
      "href": "/math/unit-6/distributive-alchemy/"
    }
  ],
  "7-1": [],
  "7-2": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "📐 Fraction & Decimal Grid Architect",
      "href": "/math/unit-7/grid-architect/"
    },
    {
      "text": "🦘 Number Line Jumper",
      "href": "/math/unit-7/6-ns-c-3game/"
    }
  ],
  "7-3": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🌡️ Temperature Explorer",
      "href": "/math/unit-7/6-ns-c-5game/"
    },
    {
      "text": "🏔️ Sub-Zero Ledger & Altitude Compass",
      "href": "/math/unit-7/subzero-ledger/"
    }
  ],
  "7-4": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🦘 Number Line Jumper",
      "href": "/math/unit-7/6-ns-c-3game/"
    },
    {
      "text": "🏔️ Sub-Zero Ledger & Altitude Compass",
      "href": "/math/unit-7/subzero-ledger/"
    }
  ],
  "7-5": [
    {
      "text": "🏆 Culminating Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🧭 Cartesian Odyssey",
      "href": "/cartesian-odyssey/"
    },
    {
      "text": "🏴‍☠️ Archipelago Coordinate Navigator",
      "href": "/math/unit-7/coordinate-navigator/"
    },
    {
      "text": "📖 Treasure Map Navigator (Part 1)",
      "href": "/graphic-novels/unit9/graphic-novel-1.html"
    }
  ],
  "7-6": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🏙️ City Builder",
      "href": "/math/unit-7/6-ns-c-8game/"
    },
    {
      "text": "📏 Cartesian Coordinate Quest — Reflections & Distance",
      "href": "/math/unit-7/coordinate-quest/"
    },
    {
      "text": "🧪 Coordinate Plane Explorer — Study Guide",
      "href": "/math/unit-7/6-ns-cstudypractice/"
    }
  ],
  "7-7": [],
  "7-8": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🏴‍☠️ Archipelago Coordinate Navigator",
      "href": "/math/unit-7/coordinate-navigator/"
    },
    {
      "text": "🗺️ Coordinate Treasure Hunt",
      "href": "/math/unit-7/6-ns-c-6game/"
    },
    {
      "text": "📖 Treasure Map Navigator (Part 2)",
      "href": "/graphic-novels/unit9/graphic-novel-2.html"
    }
  ],
  "7-9": [
    {
      "text": "🏆 Project — Coordinate Plane & Integers in Action",
      "href": "/math/unit-7/projects/"
    },
    {
      "text": "🪞 Cartesian Coordinate Quest — Reflections & Distance",
      "href": "/math/unit-7/coordinate-quest/"
    },
    {
      "text": "🏴‍☠️ Archipelago Coordinate Navigator",
      "href": "/math/unit-7/coordinate-navigator/"
    }
  ],
  "8-1": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "🔤 Word-to-Equations Sandbox",
      "href": "/word-to-equations/"
    },
    {
      "text": "📓 Detective Case Files: The Equation Mysteries (Novel #1)",
      "href": "/graphic-novels/unit7/graphic-novel-1.html"
    }
  ],
  "8-2": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "⚔️ One-Step Solver Arena",
      "href": "/math/unit-8/one-step-solver-arena/"
    },
    {
      "text": "📓 Detective Case Files: The Equation Mysteries (Novel #1)",
      "href": "/graphic-novels/unit7/graphic-novel-1.html"
    }
  ],
  "8-3": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "⚔️ One-Step Solver Arena",
      "href": "/math/unit-8/one-step-solver-arena/"
    },
    {
      "text": "📓 Detective Case Files: The Equation Mysteries (Novel #2)",
      "href": "/graphic-novels/unit7/graphic-novel-2.html"
    }
  ],
  "8-4": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "🟢 Neon Inequality Gatekeeper",
      "href": "/math/unit-8/neon-inequality/"
    },
    {
      "text": "📓 Detective Case Files: The Equation Mysteries (Novel #2)",
      "href": "/graphic-novels/unit7/graphic-novel-2.html"
    }
  ],
  "8-5": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "🟢 Neon Inequality Gatekeeper",
      "href": "/math/unit-8/neon-inequality/"
    }
  ],
  "8-6": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "🟢 Neon Inequality Gatekeeper",
      "href": "/math/unit-8/neon-inequality/"
    },
    {
      "text": "⚔️ One-Step Solver Arena",
      "href": "/math/unit-8/one-step-solver-arena/"
    }
  ],
  "8-7": [
    {
      "text": "🏆 Project — Equations & Inequalities in Action",
      "href": "/math/unit-8/projects/"
    },
    {
      "text": "🔤 Word-to-Equations Sandbox",
      "href": "/word-to-equations/"
    },
    {
      "text": "⚔️ One-Step Solver Arena",
      "href": "/math/unit-8/one-step-solver-arena/"
    },
    {
      "text": "🟢 Neon Inequality Gatekeeper",
      "href": "/math/unit-8/neon-inequality/"
    }
  ],
  "9-1": [],
  "9-2": [],
  "9-3": [],
  "9-4": [],
  "10-1": [],
  "10-2": [],
  "10-3": [],
  "10-4": [],
  "10-5": [],
  "10-6": []
};
