/* Pure mission models: every route has a valid construction; native scoring stays separate. */
(() => {
  'use strict';
  const svg = content => `<svg viewBox="0 0 640 240" role="img" aria-label="Live model of your mission construction">${content}</svg>`;
  const label = (x, y, text, color = '#eef5fb') => `<text x="${x}" y="${y}" fill="${color}" font-family="system-ui,sans-serif" font-size="19" text-anchor="middle">${text}</text>`;
  const clean = value => Number.isFinite(value) ? value : 0;
  const tank = (x, amount, total, color) => `<rect x="${x}" y="35" width="100" height="150" rx="14" fill="#14283b" stroke="#acc7d4" stroke-width="2"/><rect x="${x + 4}" y="${181 - 142 * Math.min(1, Math.max(0, amount / total))}" width="92" height="${142 * Math.min(1, Math.max(0, amount / total))}" rx="8" fill="${color}" opacity=".8"/>`;
  const field = (name, max = 20, min = 0, value = min) => ({ label: name, min, max, value });
  function buildPuzzle(id, seed, route) {
    const n = seed % 4, variation = Math.floor(seed / 4) % 3;
    if (id === 'kitchen') {
      const eighths = 5 + (n + route + variation) % 3;
      return { text: `Blend exactly ${eighths}/8 liter of lantern nectar. Use BOTH 1/8-liter berry scoops and 1/4-liter citrus scoops. Mix the two ingredients without spilling.`, fields: [field('Berry scoops · 1/8 L', 8), field('Citrus scoops · 1/4 L', 4)], action: 'Fill the lantern', check: ([a,b]) => a > 0 && b > 0 && a + 2*b === eighths, hint: 'Rename each 1/4 liter as 2/8 liter. Add the eighths, and include some of each fruit.', explain: ([a,b]) => `${a}/8 + ${b}/4 = ${eighths}/8 liter.`, draw: values => { const [a,b] = values.map(clean); return svg(tank(90,a,8,'#ec8ca9') + tank(265,b,4,'#f5c46c') + tank(440,a+2*b,8,'#91dec6') + label(140,215,'Berry') + label(315,215,'Citrus') + label(490,215,`${a+2*b}/8 L total`)); } };
    }
    if (id === 'foundry') {
      const whole = 2 + n, den = route ? 4 : 2 + (n + variation)%3, num = route ? 2 : 1, pieces = whole*den/num;
      return { text: `A bridge needs pieces ${num}/${den} meter long, cut from ${whole} meters of cable. Set the equal cuts in each meter, then load every complete piece into the bridge kit.`, fields: [field('Equal divisions in each meter', 8,1),field(`Pieces to load · ${num}/${den} m each`,30)], action: 'Forge the bridge kit', check: ([a,b]) => a === den && b === pieces, hint: `Partition each meter using the denominator. Each finished piece uses ${num} of those divisions. Count how many pieces fit in the entire cable.`, explain: () => `${whole} ÷ ${num}/${den} = ${pieces} pieces.`, draw: values => {const [a,b]=values.map(clean); let lines=''; for(let i=0;i<=Math.min(40,a*whole);i++)lines+=`<path d="M${40+i*560/Math.max(1,a*whole)} 80v70" stroke="#f6c481" stroke-width="2"/>`; return svg(`<rect x="40" y="80" width="560" height="70" rx="8" fill="#715147"/>${lines}${label(320,45,`${whole} meters of cable`)}${label(320,200,`Bridge kit: ${b} pieces`)}`); } };
    }
    if (id === 'ratio') {
      const a = 2 + n%2, b = 3 + variation, k = 2 + route + n%2;
      return { text: `The reef filter uses mineral A : mineral B = ${a} : ${b}. Fill a ${k*(a+b)}-scoop filter with the exact blend. Both ingredients must scale by the same factor.`, fields: [field('Mineral A scoops',30),field('Mineral B scoops',30)], action: 'Restore the reef', check: ([x,y]) => x*b===y*a && x+y===k*(a+b) && x>0, hint: 'Add the two parts in one batch. Divide the total capacity by that batch size, then scale BOTH ingredients.', explain: ([x,y]) => `${x}:${y} = ${a}:${b}, with ${x+y} scoops total.`, draw: values => { const [x,y]=values.map(clean); return svg(tank(130,x,k*(a+b),'#70d8d4')+tank(410,y,k*(a+b),'#f0b778')+label(180,215,`A: ${x}`)+label(460,215,`B: ${y}`)+label(320,25,`${x+y} / ${k*(a+b)} scoops loaded`)); } };
    }
    if (id === 'rally') {
      const km = 6 + n + variation, fuel=3+route+n%2, waterRate=2+route, distance=km*fuel;
      return { text: `Travel ${distance} km to the next outpost. The rover travels ${km} km per liter of fuel. Pack ${waterRate} water bottles for EACH liter of fuel. Load only the fuel and water this trip needs.`, fields: [field('Fuel · liters',15),field('Water · bottles',30)], action: 'Depart for the outpost', check: ([a,b])=>a===fuel&&b===a*waterRate, hint: 'First divide the trip distance by kilometers per liter. Then scale the water ratio using that fuel amount.', explain: ([a,b])=>`${a} × ${km} = ${distance} km; ${b} bottles = ${waterRate} × ${a}.`, draw: values=>{const [a,b]=values.map(clean); return svg(`<path d="M40 128H600" stroke="#7d877e" stroke-width="26"/><path d="M40 128H600" stroke="#efd9a7" stroke-width="3" stroke-dasharray="12 12"/><path d="M${Math.min(545,40+a*km/distance*490)} 90h55l18 30v40h-85v-40Z" fill="#8fd0c3"/>${label(320,40,`${a*km} / ${distance} km of fuel`)}${label(320,220,`Cargo: ${b} water bottles`)}`);} };
    }
    if (id === 'discount') {
      const cells=6+2*n+2*route, budget=cells/2*15;
      return { text: `Deliver exactly ${cells} solar cells with a $${budget} budget. Amber packs hold 2 cells: $20 with 25% off. Violet packs hold 3 cells: $30 with 20% off. Build a cargo that fits the budget.`, fields:[field('Amber packs · 2 cells each',12),field('Violet packs · 3 cells each',12)],action:'Send the supply cargo',check:([a,b])=>2*a+3*b===cells&&15*a+24*b<=budget,hint:'Calculate each discounted PACK price before comparing costs per cell. Then check both your total cells and spending.',explain:([a,b])=>`Amber costs $15 per pack; Violet costs $24. Your ${cells} cells cost $${15*a+24*b}.`,draw:values=>{const[a,b]=values.map(clean);let boxes='';for(let i=0;i<Math.min(16,a+b);i++)boxes+=`<rect x="${40+i%8*71}" y="${65+Math.floor(i/8)*58}" width="58" height="44" rx="5" fill="${i<a?'#e6b86f':'#b49bd8'}"/>`;return svg(boxes+label(320,30,`${2*a+3*b} / ${cells} solar cells packed`)+label(320,225,`Budget: $${budget} · calculate your total before shipping`));} };
    }
    if (id === 'area') {
      const length=3+route, width=3+n%2, height=2+n+variation, area=length*width+2*height;
      return {text:`Design a district covering exactly ${area} square units. Your rectangular hall has length ${length}. Your triangular garden has base 4. Choose the hall’s width and garden’s perpendicular height; each must be at least 2.`,fields:[field('Hall width',8,2),field('Garden height',8,2)],action:'Build the district',check:([w,h])=>length*w+2*h===area,hint:'Add rectangle area (length × width) and triangle area (base × perpendicular height ÷ 2). Several valid designs may work.',explain:([w,h])=>`${length} × ${w} + (4 × ${h}) ÷ 2 = ${area} square units.`,draw:values=>{const[w,h]=values.map(clean);return svg(`<rect x="70" y="${205-w*19}" width="${length*30}" height="${w*19}" fill="#78bdb2" stroke="#bcf2da" stroke-width="3"/><path d="M350 205H550L450 ${205-h*19}Z" fill="#b7d984" stroke="#d9edb8" stroke-width="3"/><path d="M450 205V${205-h*19}" stroke="#315947" stroke-width="2" stroke-dasharray="6 5"/>${label(140,230,`Hall: ${length} × ${w}`)}${label(450,230,`Garden: base 4, height ${h}`)}`);} };
    }
    if (id === 'expression') {
      const x=2+n+variation, goal=route?x*2+3:(x+2)*3, ops=['+','×'];
      return {text:`Send input ${x} through two connected machines. The first combines the input with 2; the second combines that output with 3. Rewire the operations to produce exactly ${goal} units of power.`,fields:[{label:'First machine',options:['Add 2','Multiply by 2']},{label:'Second machine',options:['Add 3','Multiply by 3']}],action:'Power the heart engine',check:([a,b])=>{const mid=a?x*2:x+2;return(b?mid*3:mid+3)===goal;},hint:'Follow the circuit from left to right. The second machine uses the FIRST machine’s output, not the starting input.',explain:([a,b])=>`(${x} ${ops[a]} 2) ${ops[b]} 3 = ${goal}.`,draw:values=>{const[a,b]=values.map(clean);return svg(`<path d="M65 120H575" stroke="#639fa0" stroke-width="9"/>${[150,340,535].map((x,i)=>`<circle cx="${x}" cy="120" r="${i===2?43:59}" fill="#254a5b" stroke="#9cdbbf" stroke-width="5"/>`).join('')}${label(45,90,String(x))}${label(150,125,`${ops[a]||'?'} 2`)}${label(340,125,`${ops[b]||'?'} 3`)}${label(535,125,'?')}${label(320,220,`Target output: ${goal}`)}`);} };
    }
    if (id === 'equation') {
      const weight=4+n+variation, offset=3+route*3+n, total=weight+offset;
      return {text:`The gate is balanced: x + ${offset} = ${total}. Remove the same number of counterweights from BOTH sides to isolate x. Then set the gate’s hidden weight.`,fields:[field('Weights removed from left',20),field('Weights removed from right',20),field('Hidden weight x',20)],action:'Unlock the balanced gate',check:([a,b,x])=>a===offset&&b===offset&&x===weight,hint:'Keep equality by making the same change on both sides. Remove only the extra weights next to x, then read what remains on the right.',explain:()=>`Subtract ${offset} from both sides: x = ${total} − ${offset} = ${weight}.`,draw:values=>{const[a,b,x]=values.map(clean);return svg(`<path d="M320 60V205m-75 0h150M100 85h440M160 85v75m320-75v75" stroke="#b6ac87" stroke-width="7"/><path d="M70 160h180l-25 24H95Zm320 0h180l-25 24H415Z" fill="#bca56c"/>${label(160,140,`x + ${offset-a}`)}${label(480,140,String(total-b))}${label(320,235,`Hidden weight: ${x}`)}`);} };
    }
    if (id === 'variable') {
      const k=2+n%2,b=route?3+variation:0,min=2+n%3,maxY=k*(min+2)+b;
      return {text:`Place a relay on the signal path y = ${k}x + ${b}. Choose x at least ${min}; the relay’s y-coordinate cannot exceed ${maxY}. Every valid location connects a different part of the sector.`,fields:[field('Horizontal coordinate x',10),field('Vertical coordinate y',35)],action:'Connect the relay',check:([x,y])=>x>=min&&y===k*x+b&&y<=maxY,hint:'Choose an allowed x first. Multiply it by the rate, then add the starting value to find y. Check the altitude limit.',explain:([x,y])=>`(${x}, ${y}) lies on y = ${k}x + ${b}.`,draw:values=>{const[x,y]=values.map(clean);let grid='';for(let i=0;i<=10;i++)grid+=`<path d="M${60+i*50} 20v180" stroke="#7583b0" stroke-opacity=".2"/>`;for(let i=0;i<=7;i++)grid+=`<path d="M60 ${200-i*25}h500" stroke="#7583b0" stroke-opacity=".2"/>`;return svg(grid+`<path d="M60 20v180h500" fill="none" stroke="#b4c5e2" stroke-width="2"/><circle cx="${60+x*50}" cy="${200-y*5}" r="11" fill="#c8b3f2"/>`+label(330,232,`Relay (${x}, ${y}) · altitude limit ${maxY}`));} };
    }
    if (id === 'volume') {
      const total=[12,24,36,48][(n+variation)%4];
      return {text:`Build an archive pod with volume ${total} cubic units. The ${route?'wide':'tall'} cargo bay requires ${route?'length and width both at least as large as height':'height at least as large as BOTH length and width'}. Choose dimensions from 1 to 8.`,fields:[field('Length',8,1),field('Width',8,1),field('Height',8,1)],action:'Seal the archive pod',check:([l,w,h])=>l*w*h===total&&(route?l>=h&&w>=h:h>=l&&h>=w),hint:'Find three factors of the target volume. Then turn the box so it also fits the cargo bay’s shape rule.',explain:([l,w,h])=>`${l} × ${w} × ${h} = ${total} cubic units, and the pod fits its bay.`,draw:values=>{const[l,w,h]=values.map(clean);const x=260,y=210,dx=l*22,dy=w*12,dz=h*17;return svg(`<path d="M${x} ${y}l${dx} -${dx/2}v-${dz}l-${dx} ${dx/2}Z" fill="#4898aa" stroke="#9de5dc" stroke-width="2"/><path d="M${x} ${y}l-${dy} -${dy/2}v-${dz}l${dy} ${dy/2}Z" fill="#306c91" stroke="#9de5dc" stroke-width="2"/><path d="M${x} ${y-dz}l${dx} -${dx/2}l-${dy} -${dy/2}l-${dx} ${dx/2}Z" fill="#94cdc6" stroke="#c4eae0" stroke-width="2"/>${label(500,80,`L ${l} · W ${w} · H ${h}`)}${label(500,115,`Target: ${total} units³`)}`);} };
    }
    const base=4+n+variation+route, data=[base,base+2,base+2,base+4,base+22];
    return {text:`Scout these five practice scores: ${data.join(', ')}. Flag the unusually high score for investigation, then find the median of ALL five scores. Keep every score in the dataset while you calculate.`,fields:[{label:'Score to investigate',options:data.map((v,i)=>`Practice ${i+1}: ${v}`)},field('Median of all five scores',40)],action:'Submit the scouting report',check:([index,median])=>index===4&&median===base+2,hint:'The median is the middle score after ordering ALL five values. Look for a score much farther from the others; do not remove it before finding the median.',explain:()=>`${base+2} is the middle score. The score ${base+22} is unusually high and deserves investigation.`,draw:values=>{const[index,median]=values.map(clean);return svg(data.map((v,i)=>`<rect x="${65+i*105}" y="${205-v*5}" width="65" height="${v*5}" rx="5" fill="${index===i?'#f2c178':'#76b7c9'}"/>${label(97+i*105,230,String(v))}`).join('')+label(320,25,`All 5 scores retained · proposed median ${median}`));}};

  }

  window.FlagshipPuzzles = Object.freeze({ create: buildPuzzle });
})();
