/* Nightly Hebrew — the alphabet itself: letters, vowels, and the pairs that
 * actually get confused.
 *
 * The nine innings live in `units.js`, which loads AFTER this file and hangs
 * `UNITS` off the same `HEB_DATA` object. The split is deliberate: this file is
 * the alphabet (it changes almost never) and that one is the curriculum (it
 * changes whenever the scope & sequence does).
 *
 * Plain script (no ES module) so every unit page can just <script src> it.
 */
(function (global) {
  "use strict";

  // ---------------------------------------------------------------- letters
  // c      = the consonant sound, spelled the way it is READ (used to build
  //          transliterations: c + vowel.v). This is the whole point of the
  //          app — the kid must see that a letter carries a sound and the
  //          vowel says what to do with it.
  // say    = plain-English anchor for that sound.
  // note   = what the shape looks like.
  // watch  = the look-alike letter that actually trips readers up (prose).
  // look   = the same look-alikes as bare characters, for the drills.
  // trace  = how the hand draws it, said out loud. Naming the strokes is what
  //          makes ד and ר stop swapping — you cannot mix up two shapes you
  //          have described differently.
  // final  = true for the five end-of-word forms.
  const LETTERS = {
    י: {
      name: "Yud",
      c: "y",
      say: "y like in yes",
      note: "The smallest letter — it floats up high.",
      watch: "",
      look: ["ו"],
      trace: "One short comma up near the ceiling. Never touches the line.",
    },
    ו: {
      name: "Vav",
      c: "v",
      say: "v like in van",
      note: "One straight line with a little hat.",
      watch: "ז — Zayin's hat sticks out on BOTH sides; Vav's leans right.",
      look: ["ז", "ן", "י"],
      trace: "Little hat on top, then straight down to the line. Stop at the line.",
    },
    ז: {
      name: "Zayin",
      c: "z",
      say: "z like in zoo",
      note: "A line with a wide hat, like a bat over a stick.",
      watch: "ו — Vav has a smaller hat.",
      look: ["ו", "ן"],
      trace: "Wide hat across the top, then drop the stick from the MIDDLE of the hat.",
    },
    ר: {
      name: "Resh",
      c: "r",
      say: "r like in run",
      note: "Round shoulder, no corner in the back.",
      watch: "ד — Dalet has a sharp corner and a little heel sticking out back.",
      look: ["ד", "ך"],
      trace: "Across the top, then curve down in one smooth round shoulder. No heel.",
    },
    ד: {
      name: "Dalet",
      c: "d",
      say: "d like in dog",
      note: "Sharp corner on top, with a heel poking out to the right.",
      watch: "ר — Resh is rounded with no heel.",
      look: ["ר", "ך"],
      trace: "Across the top past the corner — that overhang IS the heel — then straight down.",
    },
    ה: {
      name: "Hey",
      c: "h",
      say: "h like in hat",
      note: "Like a Dalet with a little leg that does NOT touch the roof.",
      watch: "ח — Chet's left leg IS attached to the roof.",
      look: ["ח", "ת"],
      trace: "Draw a Dalet, then add a separate short leg on the left. Leave the gap.",
    },
    ח: {
      name: "Chet",
      c: "ch",
      say: "ch from the throat, like Bach or challah",
      note: "Two legs joined right across the top — no gap.",
      watch: "ה — Hey has a gap; ת — Tav's left leg has a foot.",
      look: ["ה", "ת"],
      trace: "One roof all the way across, then a leg down each end. Sealed on top.",
    },
    ת: {
      name: "Tav",
      c: "t",
      say: "t like in top",
      note: "Left leg has a foot kicking to the left.",
      watch: "ח — Chet has no foot.",
      look: ["ח", "ה", "ט"],
      trace: "Roof across, right leg straight down, left leg down and then kick left.",
    },
    תּ: {
      name: "Tav (with the dot)",
      c: "t",
      say: "t like in top",
      note: "The dot doesn't change the sound here — still t.",
      watch: "",
      look: ["ת"],
      trace: "Same Tav, with a dot parked inside it.",
    },
    ק: {
      name: "Kuf",
      c: "k",
      say: "k like in kick",
      note: "Its left leg drops BELOW the line — the only letter that does.",
      watch: "",
      look: ["ר"],
      trace: "Roof and a round back like a Resh, then a leg on the left that dives under the line.",
    },
    נ: {
      name: "Nun",
      c: "n",
      say: "n like in no",
      note: "A narrow hook sitting on the line.",
      watch: "ג — Gimel has a foot that kicks left.",
      look: ["ג"],
      trace: "Short roof, straight down, then a tiny turn LEFT along the line.",
    },
    כּ: {
      name: "Kaf (dot inside)",
      c: "k",
      say: "k like in king",
      note: "Dot inside = the hard k sound.",
      watch: "בּ — Bet's bottom line sticks out to the right.",
      look: ["בּ", "כ"],
      trace: "One round C-shape facing left, dot in the belly. Bottom stays tucked in.",
    },
    כ: {
      name: "Chaf (no dot)",
      c: "ch",
      say: "ch from the throat, like Bach",
      note: "Take the dot out and it turns breathy.",
      watch: "ב — Vet has a bottom line that sticks out.",
      look: ["ב", "כּ"],
      trace: "The same round C-shape, empty belly.",
    },
    בּ: {
      name: "Bet (dot inside)",
      c: "b",
      say: "b like in ball",
      note: "Dot inside = b. Bottom line pokes out on the right.",
      watch: "כּ — Kaf has no poking-out bottom.",
      look: ["כּ", "ב"],
      trace: "Down the right side, along the bottom, and let the bottom line stick out right.",
    },
    ב: {
      name: "Vet (no dot)",
      c: "v",
      say: "v like in van",
      note: "Same letter, no dot, new sound.",
      watch: "כ — Chaf is fully rounded.",
      look: ["כ", "בּ"],
      trace: "Same shape as Bet with the poking-out foot — just no dot inside.",
    },
    פּ: {
      name: "Pey (dot inside)",
      c: "p",
      say: "p like in play",
      note: "Dot inside = p. There's a little curl tucked inside.",
      watch: "",
      look: ["פ"],
      trace: "Round outside like a Chaf, then tuck a little curl in at the top. Dot in the belly.",
    },
    פ: {
      name: "Fey (no dot)",
      c: "f",
      say: "f like in fun",
      note: "Drop the dot and p turns into f.",
      watch: "",
      look: ["פּ"],
      trace: "Same curl-inside shape, empty belly.",
    },
    ג: {
      name: "Gimel",
      c: "g",
      say: "g like in go (never like giant)",
      note: "A foot kicking out to the left.",
      watch: "נ — Nun has no kicking foot.",
      look: ["נ"],
      trace: "Short stroke down, then a foot that kicks out to the LEFT at the bottom.",
    },
    ל: {
      name: "Lamed",
      c: "l",
      say: "l like in look",
      note: "The tallest letter — its neck sticks up above the line.",
      watch: "",
      look: [],
      trace: "Start ABOVE the ceiling, swing the tall neck down and around to the left.",
    },
    מ: {
      name: "Mem",
      c: "m",
      say: "m like in mom",
      note: "Closed box with a little notch on the left.",
      watch: "ס — Samech is fully closed and round.",
      look: ["ס", "ם"],
      trace: "A box — but leave a tiny notch open at the bottom left.",
    },
    ם: {
      name: "Final Mem",
      c: "m",
      say: "m like in mom",
      note: "The closed square Mem — only ever at the END of a word.",
      watch: "ס — Samech is rounder.",
      look: ["ס", "מ"],
      final: true,
      trace: "A completely sealed square. No notch anywhere.",
    },
    ס: {
      name: "Samech",
      c: "s",
      say: "s like in sun",
      note: "A closed circle — no notch, no gap.",
      watch: "ם — Final Mem is square-ish.",
      look: ["ם", "מ"],
      trace: "One smooth closed circle, corners rounded off.",
    },
    שׁ: {
      name: "Shin (dot on the RIGHT)",
      c: "sh",
      say: "sh like in shoe",
      note: "Three branches. Dot up on the RIGHT arm.",
      watch: "שׂ — Sin's dot is on the LEFT.",
      look: ["שׂ"],
      trace: "Three branches out of one cup, then park the dot on the RIGHT branch.",
    },
    שׂ: {
      name: "Sin (dot on the LEFT)",
      c: "s",
      say: "s like in sun",
      note: "Same three branches, dot on the LEFT arm.",
      watch: "שׁ — Shin's dot is on the RIGHT.",
      look: ["שׁ"],
      trace: "Three branches out of one cup, then park the dot on the LEFT branch.",
    },
    ט: {
      name: "Tet",
      c: "t",
      say: "t like in top",
      note: "A pot with a curl tucked inside on the left.",
      watch: "ת — Tav is two separate legs.",
      look: ["ת"],
      trace: "A wide open pot, then curl the left side inward like a handle.",
    },
    ע: {
      name: "Ayin",
      c: "",
      say: "SILENT — it makes no sound of its own",
      note: "A V on a stick. It just carries the vowel.",
      watch: "א — Alef is also silent; Ayin looks like a Y/V shape.",
      look: ["א", "צ"],
      trace: "Two arms meeting in a V, then one leg down from the joint.",
    },
    א: {
      name: "Alef",
      c: "",
      say: "SILENT — it makes no sound of its own",
      note: "The very first letter, and it has no sound! It holds a vowel for you.",
      watch: "ע — Ayin is the other silent one.",
      look: ["ע"],
      trace: "One diagonal slash, then a little Yud clipped to the top and one to the bottom.",
    },
    צ: {
      name: "Tzadi",
      c: "tz",
      say: "tz like the end of cats",
      note: "Two strokes joining, with a foot to the left.",
      watch: "ע — Ayin is silent; Tzadi is a real ts sound.",
      look: ["ע", "ץ"],
      trace: "A V of arms like Ayin, but the bottom kicks out to the LEFT like a Nun.",
    },
    ן: {
      name: "Final Nun",
      c: "n",
      say: "n like in no",
      note: "Straight down BELOW the line. End of a word only.",
      watch: "ו — Vav stops at the line; Final Nun keeps going down.",
      look: ["ו", "ז"],
      final: true,
      trace: "Little hat, then one long straight line that keeps going UNDER the line.",
    },
    ך: {
      name: "Final Chaf",
      c: "ch",
      say: "ch from the throat, like Bach",
      note: "Long tail below the line. End of a word only.",
      watch: "ר — Resh stops on the line.",
      look: ["ר", "ד"],
      final: true,
      trace: "Roof across, then drop the back wall straight down past the line.",
    },
    ףּ: {
      name: "Final Fey",
      c: "f",
      say: "f like in fun",
      note: "Long tail below the line. End of a word only.",
      watch: "",
      look: ["ף"],
      final: true,
      trace: "The Fey curl, with a tail that dives below the line.",
    },
    ף: {
      name: "Final Fey",
      c: "f",
      say: "f like in fun",
      note: "Long tail below the line. End of a word only.",
      watch: "ן — Final Nun has no head on top.",
      look: ["ן", "ץ"],
      final: true,
      trace: "Roof and the little inside curl, then a long tail below the line.",
    },
    ץ: {
      name: "Final Tzadi",
      c: "tz",
      say: "tz like the end of cats",
      note: "Long tail below the line. End of a word only.",
      watch: "ן — Final Nun is a plain straight line.",
      look: ["ן", "ף", "צ"],
      final: true,
      trace: "The Tzadi arms, but instead of a foot the leg runs straight down below the line.",
    },
  };

  // ----------------------------------------------------------------- vowels
  // ch is appended straight after the letter — that string concatenation is
  // exactly what a reader does out loud: letter first, then vowel.
  // family = the sound group, so "which vowels say ah?" is answerable in code
  //          instead of being a fact an adult has to keep repeating.
  const VOWELS = {
    kamatz: {
      ch: "ָ",
      name: "Kamatz",
      v: "ah",
      family: "ah",
      say: "ah like in father",
      art: "a little T sitting under the letter",
    },
    patach: {
      ch: "ַ",
      name: "Patach",
      v: "ah",
      family: "ah",
      say: "ah like in father",
      art: "a flat line under the letter",
    },
    tzere: {
      ch: "ֵ",
      name: "Tzere",
      v: "ay",
      family: "ay",
      say: "ay like in they",
      art: "two dots side by side",
    },
    segol: {
      ch: "ֶ",
      name: "Segol",
      v: "eh",
      family: "eh",
      say: "eh like in bed",
      art: "three dots in a little triangle",
    },
    chirik: {
      ch: "ִ",
      name: "Chirik",
      v: "ee",
      family: "ee",
      say: "ee like in see",
      art: "one single dot",
    },
    chirikMalei: {
      ch: "ִי",
      name: "Chirik + Yud",
      v: "ee",
      family: "ee",
      say: "ee like in see",
      art: "the dot, plus a Yud right after — still just ee",
    },
    tzereYud: {
      ch: "ֵי",
      name: "Tzere + Yud",
      v: "ay",
      family: "ay",
      say: "ay like in they",
      art: "two dots plus a Yud — still just ay",
    },
    sheva: {
      ch: "ְ",
      name: "Sheva",
      v: "'",
      family: "quiet",
      say: "mostly SILENT — a tiny quick 'uh' at most",
      art: "two dots stacked up and down",
    },
    cholam: {
      ch: "ֹ",
      name: "Cholam",
      v: "oh",
      family: "oh",
      say: "oh like in go",
      art: "one dot up on the LEFT shoulder",
    },
    cholamMalei: {
      ch: "וֹ",
      name: "Cholam + Vav",
      v: "oh",
      family: "oh",
      say: "oh like in go",
      art: "a Vav with a dot on top — still just oh",
    },
    shuruk: {
      ch: "וּ",
      name: "Shuruk",
      v: "oo",
      family: "oo",
      say: "oo like in moon",
      art: "a Vav with a dot in its belly",
    },
    kubutz: {
      ch: "ֻ",
      name: "Kubutz",
      v: "oo",
      family: "oo",
      say: "oo like in moon",
      art: "three dots climbing up to the left",
    },
    chatafPatach: {
      ch: "ֲ",
      name: "Chataf Patach",
      v: "ah",
      family: "ah",
      say: "a quick little ah",
      art: "a Sheva glued onto a Patach",
    },
    chatafSegol: {
      ch: "ֱ",
      name: "Chataf Segol",
      v: "eh",
      family: "eh",
      say: "a quick little eh",
      art: "a Sheva glued onto a Segol",
    },
    chatafKamatz: {
      ch: "ֳ",
      name: "Chataf Kamatz",
      v: "oh",
      family: "oh",
      say: "a quick little oh",
      art: "a Sheva glued onto a Kamatz",
    },
  };

  // ------------------------------------------------------------ confusables
  // Groups of shapes that genuinely get swapped while reading. The look-alike
  // drills only ever offer a group whose members are ALL already taught, so a
  // kid is never asked to rule out a letter he has not met.
  const CONFUSABLES = [
    {
      chars: ["ר", "ד"],
      why: "Dalet has a heel poking out back; Resh is one smooth round shoulder.",
    },
    { chars: ["ו", "ז"], why: "Zayin's hat crosses on both sides; Vav's hat only leans right." },
    { chars: ["ה", "ח"], why: "Hey has a GAP at the top left; Chet is sealed all the way across." },
    {
      chars: ["ח", "ת"],
      why: "Tav's left leg kicks out into a foot; Chet's leg goes straight down.",
    },
    { chars: ["ה", "ת"], why: "Hey's left leg floats free; Tav's is attached and has a foot." },
    { chars: ["ג", "נ"], why: "Gimel kicks a foot to the left; Nun turns only a little." },
    { chars: ["בּ", "כּ"], why: "Bet's bottom line pokes out to the right; Kaf stays tucked in." },
    { chars: ["ב", "כ"], why: "Vet's bottom line pokes out to the right; Chaf is fully rounded." },
    { chars: ["בּ", "ב"], why: "The dot inside makes it b. No dot makes it v." },
    { chars: ["כּ", "כ"], why: "The dot inside makes it k. No dot makes it the throaty ch." },
    { chars: ["פּ", "פ"], why: "The dot inside makes it p. No dot makes it f." },
    { chars: ["מ", "ס"], why: "Mem has a notch at the bottom left; Samech is a sealed circle." },
    { chars: ["ם", "ס"], why: "Final Mem is squared off; Samech is round." },
    {
      chars: ["מ", "ם"],
      why: "Plain Mem has a notch and can go anywhere; Final Mem is sealed and only ends words.",
    },
    { chars: ["שׁ", "שׂ"], why: "Dot on the RIGHT arm says sh. Dot on the LEFT arm says s." },
    { chars: ["ט", "ת"], why: "Tet is one pot with a curl inside; Tav is two separate legs." },
    {
      chars: ["א", "ע"],
      why: "Both are silent. Alef is a slash with two Yuds; Ayin is a V on a stick.",
    },
    { chars: ["ע", "צ"], why: "Ayin is silent; Tzadi kicks a foot left and says tz." },
    { chars: ["ו", "ן"], why: "Vav stops at the line; Final Nun keeps going below it." },
    { chars: ["ר", "ך"], why: "Resh stops at the line; Final Chaf drops below it." },
    {
      chars: ["ן", "ף"],
      why: "Final Fey has a head and an inside curl; Final Nun is a plain line.",
    },
    { chars: ["ן", "ץ"], why: "Final Tzadi has two arms up top; Final Nun has none." },
    {
      chars: ["צ", "ץ"],
      why: "Tzadi kicks left on the line; Final Tzadi runs straight down past it.",
    },
  ];

  global.HEB_DATA = { LETTERS, VOWELS, CONFUSABLES };
})(window);
