/**
 * scorm-catalog.js — canonical titles and route existence for SCORM packages.
 *
 * Canvas shows the SCO title from imsmanifest.xml, and a teacher scanning a
 * course list should read "EduWonderLab — Lesson 6-2: Volume of Rectangular
 * Prisms", not "6-2-homework". There is already exactly one compiled curriculum
 * vocabulary that Pages Functions can import (`plan-vocab.js`, generated by
 * scripts/generate-plan-vocab.mjs from the curriculum manifest), so this module
 * READS that rather than starting a second copy of the titles — a second copy is
 * how a renamed lesson keeps its old name in Canvas forever.
 *
 * Pages Functions cannot read data/*.json at runtime, which is why the compiled
 * module exists at all. Run `npm run generate-plan-vocab` after adding a lesson.
 */

import { ACTIVITIES, LESSONS } from "./plan-vocab.js";

const LESSON_BY_ID = new Map(LESSONS.map((l) => [l.id, l]));
/**
 * Keyed by path AND query, because ten Practice Arcade entries share one path
 * and differ only by ?unit=N. Keying on path alone silently kept whichever
 * entry the array happened to end on, so every unit's package would have been
 * titled after Unit 10 — a teacher publishing Unit 3 would see the wrong name
 * in Canvas, and nothing about the package would look wrong.
 */
const ACTIVITY_BY_KEY = new Map(
  ACTIVITIES.map((a) => [`${normPath(a.path)}${normQuery(a.query)}`, a]),
);
const ACTIVITY_BY_ID = new Map(ACTIVITIES.filter((a) => a.id).map((a) => [String(a.id), a]));
/** Path-only fallback, but ONLY for paths a single catalog entry claims. */
const ACTIVITY_BY_PATH = new Map();
for (const a of ACTIVITIES) {
  const p = normPath(a.path);
  ACTIVITY_BY_PATH.set(p, ACTIVITY_BY_PATH.has(p) ? null : a);
}

/** The catalog-significant query, normalized: "?unit=3", "?lesson=1-3" or "". */
function normQuery(query) {
  let params;
  try {
    params = new URLSearchParams(String(query || "").replace(/^\?/, ""));
  } catch (_e) {
    return "";
  }
  const lesson = params.get("lesson");
  if (lesson) return `?lesson=${lesson}`;
  const unit = params.get("unit");
  return unit ? `?unit=${unit}` : "";
}

function normPath(p) {
  let s = String(p || "").trim();
  if (!s.startsWith("/")) s = "/" + s;
  s = s.replace(/\/{2,}/g, "/");
  if (!/\.[a-z0-9]+$/i.test(s) && !s.endsWith("/")) s += "/";
  return s.toLowerCase();
}

/** "1-1" from /lessons/1-1/..., or "" when the path is not lesson-scoped. */
function lessonIdFromPath(pathname) {
  const m = /^\/lessons\/([0-9]+-[0-9]+)(?:-[a-z0-9]+)?\//i.exec(normPath(pathname));
  return m ? m[1] : "";
}

/** The sub-resource a lesson path points at: "", "homework", "worksheet", … */
function lessonResource(pathname) {
  const segs = normPath(pathname).split("/").filter(Boolean);
  if (segs[0] !== "lessons") return "";
  const rest = segs
    .slice(2)
    .join("/")
    .replace(/index\.html$/, "")
    .replace(/\.html?$/, "");
  return rest.replace(/\/+$/, "");
}

const RESOURCE_LABELS = {
  "": "",
  homework: "Homework",
  worksheet: "Worksheet",
  readiness: "Get Ready",
  practice: "Practice",
  slides: "Slides",
  learn: "Learn It",
  printable: "Printable",
  "study-pack": "Study Pack",
};

/**
 * Canonical, human-readable title for a resolved lesson URL.
 *
 * Returns `{ title, known }`. `known:false` means the curriculum has no entry
 * for this route — the caller decides whether that is a pre-flight failure (a
 * lesson id that does not exist) or merely an un-catalogued standalone activity.
 */
export function canonicalTitle(lessonUrl) {
  let pathname = lessonUrl;
  let params = null;
  try {
    const u = new URL(lessonUrl);
    pathname = u.pathname;
    params = u.searchParams;
  } catch (_e) {
    /* already a path */
  }

  // Exact path+query first — that is the only lookup that can tell the ten
  // Practice Arcade units apart. Path-only is a fallback, and it is deliberately
  // null for any path more than one catalog entry claims.
  const key = `${normPath(pathname)}${normQuery(params ? `?${params}` : "")}`;
  const activity = ACTIVITY_BY_KEY.get(key) || ACTIVITY_BY_PATH.get(normPath(pathname));
  if (activity) return { title: `EduWonderLab — ${activity.title}`, known: true };

  const id = lessonIdFromPath(pathname);
  if (id && LESSON_BY_ID.has(id)) {
    const lesson = LESSON_BY_ID.get(id);
    const res = RESOURCE_LABELS[lessonResource(pathname)];
    // An unrecognized sub-resource still gets the lesson's real name rather
    // than falling back to a slug — the lesson title is the useful half.
    const suffix = res === undefined ? "" : res;
    return {
      title: suffix
        ? `EduWonderLab — Lesson ${id} ${suffix}`
        : `EduWonderLab — Lesson ${id}: ${lesson.title}`,
      known: true,
    };
  }

  // Not in the curriculum vocabulary. The compiled vocabulary covers every
  // lesson and 189 catalog activities, but the SCORM activity catalog is a
  // superset (the arcade/game entries live in tools/scorm/activity-catalog.json,
  // which a Pages Function cannot read at runtime). Rather than stand up a
  // second runtime data source, derive a READABLE title from the route itself —
  // "Practice Arcade (Unit 3)" rather than "math-games-practice-arcade-unit-3".
  // Canvas shows this string to the teacher, so a slug there is a real cost.
  return { title: `EduWonderLab — ${humanize(pathname, params)}`, known: false };
}

/** Title-case the meaningful part of a route, with its unit/lesson qualifier. */
function humanize(pathname, params) {
  const segs = normPath(pathname).split("/").filter(Boolean);
  const last = (segs.pop() || "activity").replace(/\.html?$/i, "").replace(/^index$/, "");
  const words = (last || segs.pop() || "activity")
    .split(/[-_]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  const lesson = params?.get("lesson");
  const unit = params?.get("unit");
  const qualifier = lesson ? ` (Lesson ${lesson})` : unit ? ` (Unit ${unit})` : "";
  return `${words}${qualifier}`;
}

/**
 * Does this route exist in the canonical curriculum?
 *
 * Only ever authoritative in the NEGATIVE for lesson ids: a `/lessons/9-9/`
 * target whose id is absent from the manifest is a typo, and packaging it would
 * hand a teacher a zip that iframes a 404. Standalone activity paths are not
 * exhaustively catalogued (the site holds many hand-built activity folders), so
 * an unknown non-lesson path is reported UNKNOWN, never missing — a pre-flight
 * check that fails on everything it has not heard of stops teachers shipping
 * legitimate packages.
 */
export function routeKnown(lessonUrl) {
  let pathname = lessonUrl;
  try {
    pathname = new URL(lessonUrl).pathname;
  } catch (_e) {
    /* already a path */
  }
  if (ACTIVITY_BY_PATH.has(normPath(pathname))) return "known";
  const segs = normPath(pathname).split("/").filter(Boolean);
  if (segs[0] === "lessons") {
    const id = lessonIdFromPath(pathname);
    // Only a CURRICULUM-SHAPED id (unit-lesson digits, optionally with a
    // generated variant suffix like 1-1-group2) is something this module has
    // authority over. `/lessons/<word-slug>/` is outside the manifest's
    // vocabulary entirely, so it is UNKNOWN — reporting it missing would fail
    // pre-flight on every legitimate route the catalog does not enumerate,
    // which is a pre-flight that stops teachers shipping working packages.
    if (!id) return "unknown";
    return LESSON_BY_ID.has(id) ? "known" : "missing";
  }
  return "unknown";
}

/**
 * Short, human-readable name for a PACKAGE ID — the half of a download filename
 * a teacher actually reads.
 *
 * Deliberately derived from the id alone and from nothing the caller passes in.
 * Three builders write packages (`/api/scorm`, `build-scorm.mjs`, the Canvas
 * packages page) and one of them copies files BY NAME, so a filename that
 * varied with an optional title argument would go back to the ENOENT class of
 * bug the id argument was restored to fix. Same id → same filename, always.
 */
export function shortNameForId(id) {
  const raw = String(id || "");
  // Mode/personalization suffixes are carried elsewhere in the filename.
  const base = raw.replace(/-codes$/, "").replace(/-supports-.*$/, "");

  const bare = /^(\d+-\d+)$/.exec(base);
  if (bare) {
    const lesson = LESSON_BY_ID.get(bare[1]);
    return lesson ? titleSlug(lesson.title) : "";
  }
  const scoped = /^(\d+-\d+)-(.+)$/.exec(base);
  if (scoped) {
    const label = RESOURCE_LABELS[scoped[2]];
    if (label) return titleSlug(label);
    // An unrecognized sub-resource keeps its own words rather than borrowing
    // the lesson's title, which would make homework and worksheet packages read
    // as the same thing.
    return titleSlug(scoped[2].replace(/-/g, " "));
  }
  // The catalog id first (that is what the query-variant packages are named
  // after), then the path. Without the id lookup all ten Practice Arcade
  // packages would download with no readable title at all.
  const activity = ACTIVITY_BY_ID.get(base) || ACTIVITY_BY_PATH.get(normPath(`/${base}/`));
  return activity ? titleSlug(activity.title) : "";
}

/** Short, filesystem-safe title fragment for a download filename. */
export function titleSlug(title, max = 44) {
  return (
    String(title || "")
      // Drop the brand prefix and the lesson-number prefix: the filename already
      // carries both, and repeating them costs the part a teacher actually reads.
      .replace(/^EduWonderLab\s*—\s*/i, "")
      .replace(/^Lesson\s+[0-9]+-[0-9]+\s*[:.]?\s*/i, "")
      .replace(/[^A-Za-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, max)
      .replace(/_+$/g, "")
  );
}
