// Editorial source. Every brief is intentional; lesson coverage is validated.
function lab(id, lessons, title, icon, mission, kind, mode, values, investigate, create, finale) {
  return {
    id,
    lessons: lessons.split(" "),
    title,
    icon,
    mission,
    model: { kind, mode, values },
    investigate,
    create,
    finale,
  };
}
export const blueprints = [
  lab(
    "math-detectives",
    "1-1 1-2",
    "The Everyday Math Detective Agency",
    "🔎",
    "Find the mathematics hiding in everyday decisions. Build an estimate, test a strategy, and explain why another person could reason differently.",
    "array",
    "estimate",
    [8, 6],
    [
      "Before counting, estimate how many seats the seating plan holds. What did you use as an anchor?",
      "Change the rows but keep the total number of seats. Find two different arrangements.",
      "Which arrangement is easier to count? Explain how grouping helps you check your estimate.",
    ],
    "Design seating for 48 people. Draw two arrangements, explain how you know each fits 48, and describe one math strength you used.",
    "Case Closed",
  ),
  lab(
    "neighborhood-makers",
    "1-3 1-4",
    "Neighborhood Makers Market",
    "🏘️",
    "Plan a tiny market stall. Make sensible money decisions and persuade another designer using a clear model and calculation.",
    "decimal",
    "budget",
    [3.5, 4],
    [
      "Predict the cost of four items priced $3.50 before checking.",
      "Make an order that costs exactly $18. Can you find two ways?",
      "Explain why changing the number of items changes the total multiplicatively.",
    ],
    "Plan a stall purchase with a $25 budget. Record the price, quantity, total, and change. Write a convincing explanation of why the plan stays within budget.",
    "Market Day",
  ),
  lab(
    "pattern-studio",
    "1-5 1-6",
    "Pattern Studio Collective",
    "🧵",
    "Build a growing pattern that a partner can continue. Share the rule, compare strategies, and revise the design together.",
    "growth",
    "tiles",
    [3, 2, 4],
    [
      "Build stages 1, 2, and 3. What stays the same and what changes?",
      "Find two rules that both give 14 tiles at stage 4. Does that make the patterns identical?",
      "Trade your rule with a partner and predict stage 10 without drawing every stage.",
    ],
    "Invent a pattern with a fixed starting part and a repeating addition. Give the first four stages, a rule, and one question that invites a partner to help improve it.",
    "Pattern Relay",
  ),
  lab(
    "data-newsroom",
    "2-1 2-2",
    "The Data Newsroom",
    "📰",
    "Investigate a question whose answers vary. Turn the data into an honest histogram and choose a headline the evidence supports.",
    "data",
    "histogram",
    [4, 5, 7, 8, 9, 12, 14, 15],
    [
      "Group the data into intervals of width 5. Count every value exactly once.",
      "Move a value across an interval boundary. Which bars change?",
      "Write a statistical question that could produce these data. Name the group and the measurement.",
    ],
    "Write a newsroom report with a statistical question, a labeled histogram, and a headline. Explain one claim your graph cannot support.",
    "Headline Hunt",
  ),
  lab(
    "middle-ground",
    "2-3 2-4",
    "The Middle Ground Observatory",
    "🔭",
    "Help an observatory describe a week of observations. Find the middle and show the spread with a five-number summary.",
    "data",
    "box",
    [2, 4, 5, 7, 9, 10, 12, 15],
    [
      "Find the two middle values and use them to explain the median.",
      "Change only the largest value. What changes in the box plot and what stays fixed?",
      "Explain why a box plot does not tell you every individual observation.",
    ],
    "Create eight observations with median 8. Draw a box plot and explain how you found the median and quartiles. Use the median-of-halves convention shown here.",
    "Observatory Signals",
  ),
  lab(
    "consistency-cup",
    "2-5",
    "The Consistency Cup",
    "🎯",
    "Compare how spread out a team’s results are. Decide whether the range or the middle half tells the more useful story.",
    "data",
    "spread",
    [3, 4, 5, 5, 6, 7, 8, 10],
    [
      "Predict the range and interquartile range of the starting results.",
      "Keep the median fixed while increasing the range. What did you change?",
      "Make the middle half more tightly grouped without changing the minimum or maximum.",
    ],
    "Build two sets of eight results with the same range but different interquartile ranges. Explain which team is more consistent in its middle half.",
    "Precision Tournament",
  ),
  lab(
    "delivery-dispatch",
    "2-6 2-7",
    "Delivery Dispatch",
    "🚚",
    "Split supplies into equal shipments. Use division, place value, and multiplication checks to prevent a delivery mistake.",
    "division",
    "shipments",
    [144, 12],
    [
      "Predict how many equal groups fit before calculating.",
      "Try 14.4 ÷ 1.2. Why does it have the same quotient as 144 ÷ 12?",
      "Make a division problem whose quotient is 15. Show a multiplication check.",
    ],
    "Write a shipment plan using a decimal measurement. Show a division algorithm, explain any place-value shift, and check the answer by multiplication.",
    "Dispatch Desk",
  ),
  lab(
    "fair-share-festival",
    "2-8 2-9",
    "Fair Share Festival",
    "🎪",
    "Redistribute a festival’s supplies fairly, then measure how far the original amounts were from that fair share.",
    "data",
    "mean-mad",
    [2, 4, 6, 8, 10, 12, 14, 16],
    [
      "Find the total and share it equally among eight booths. That is the mean.",
      "Measure each booth’s distance from the mean. Why are the distances nonnegative?",
      "Create two data sets with the same mean and different mean absolute deviations.",
    ],
    "Make a fair-share proposal. Include the original amounts, mean, absolute deviations, and MAD. Explain what a smaller MAD would mean for the booths.",
    "Fair Share Challenge",
  ),
  lab(
    "outlier-investigation",
    "2-10",
    "The Outlier Investigation",
    "🕵️",
    "A dramatic number has changed a report. Investigate which measures still describe a typical observation honestly.",
    "data",
    "outlier",
    [5, 6, 6, 7, 7, 8, 9, 40],
    [
      "Compare the mean and median. Which one is closer to most values?",
      "Replace 40 with 10. Describe how each measure changes.",
      "Explain when keeping an unusual value is important even if it changes the summary.",
    ],
    "Write two accurate reports about the same data: one using mean and MAD, the other median and IQR. Recommend the more useful report and justify your choice.",
    "Evidence Verdict",
  ),
  lab(
    "decimal-design-shop",
    "2-11 2-12",
    "Decimal Design Shop",
    "🛍️",
    "Cost out custom designs, track spending, and catch a misplaced decimal before an order goes to production.",
    "decimal",
    "receipt",
    [2.75, 6],
    [
      "Estimate a six-item order first. Use the estimate to check the exact product.",
      "On paper, compare 2.75 × 6 with 27.5 × 6. Explain the factor-of-ten change.",
      "Design two orders whose totals differ by exactly $1.50.",
    ],
    "Create an itemized receipt for two products. Multiply to find each subtotal, add the subtotals, and subtract from $50. Include an estimate and one error a shopper should avoid.",
    "Receipt Rescue",
  ),
  lab(
    "recipe-remix",
    "3-1 3-2",
    "Recipe Remix Radio",
    "🍹",
    "Mix a signature drink and price it fairly. Keep the order of ratio quantities clear and give every unit rate its units.",
    "ratio",
    "mixer",
    [3, 2],
    [
      "Compare juice to water and juice to the whole drink. Why are their second numbers different?",
      "Double both ingredients. Explain why the recipe tastes the same.",
      "Use 6 cups of juice and 4 cups of water at a total cost of $5. What is the cost per cup of drink?",
    ],
    "Design a drink card with a part-to-part ratio, a part-to-whole ratio, and a price per cup. Show how a customer can check all three.",
    "Remix Requests",
  ),
  lab(
    "ratio-railway",
    "3-3 3-4",
    "Ratio Railway",
    "🚆",
    "Connect a table, a graph, and a constant ratio. Send trains only along a route that preserves the relationship.",
    "growth",
    "ratio-graph",
    [3, 0, 4],
    [
      "List four pairs for three passengers per carriage.",
      "Plot the pairs. Explain why this graph passes through the origin.",
      "Change the passengers per carriage. How do the table and graph change together?",
    ],
    "Make a railway timetable for a constant ratio. Include five ordered pairs, labeled axes, and an explanation of a point that does not belong.",
    "Signal Switch",
  ),
  lab(
    "mixture-matchup",
    "3-5",
    "Mixture Matchup",
    "🎨",
    "Compare two paint recipes fairly. Decide which mixture has more color for the same amount of white paint.",
    "ratio",
    "compare",
    [2, 3],
    [
      "Compare your mixture with the reference 3:5. Which has more color per cup of white?",
      "Find three mixtures equivalent to 2:3.",
      "Explain why adding one cup to both parts usually changes the mixture.",
    ],
    "Recommend one of two paint recipes for a stronger color. Show a common-quantity comparison and explain why comparing only total amounts could mislead.",
    "Color Commission",
  ),
  lab(
    "world-expedition",
    "3-6 3-7",
    "World Expedition Outfitters",
    "🧭",
    "Translate measurements for an expedition. Keep conversion factors visible and distinguish exact conversions from approximate ones.",
    "conversion",
    "expedition",
    [5, 2.54],
    [
      "Use 1 inch = 2.54 centimeters to convert five inches.",
      "Reverse the calculation to return to inches. Explain why the numbers change but the length does not.",
      "Compare that conversion with 1 foot = 12 inches. Name the starting and ending units every time.",
    ],
    "Write a packing label using two measurement systems. State the conversion factor, show both directions, and label an approximate conversion if you use one.",
    "Border Crossing",
  ),
  lab(
    "best-buy-boulevard",
    "3-8",
    "Best Buy Boulevard",
    "🛒",
    "Choose supplies for a neighborhood event. Find unit prices, compare deals, and explain when a cheaper unit price is not the whole decision.",
    "rate",
    "shopping",
    [12, 8],
    [
      "Compare your price per item with a reference pack of 6 items for $10.",
      "Build a larger pack with exactly the same unit price.",
      "If you need only three items, what else should you consider besides unit price?",
    ],
    "Create two offers, choose the better unit price, then explain a situation where the other offer might be more practical. Include units and exact calculations.",
    "Shopping List Sprint",
  ),
  lab(
    "scale-and-sail",
    "3-9 3-10",
    "Scale and Sail Workshop",
    "⛵",
    "Prepare matching model boats and full-size plans. Scale ratios consistently and convert lengths without changing the design.",
    "conversion",
    "scale",
    [4, 12],
    [
      "Use 1 foot = 12 inches to convert a four-foot mast.",
      "Build a table for masts 1, 2, 3, and 4 feet tall. What ratio stays constant?",
      "Explain why changing units can make the number larger without making the mast longer.",
    ],
    "Design a boat with three labeled lengths in feet and inches. Prove that each pair is equivalent, then scale all three lengths by the same factor.",
    "Harbor Launch",
  ),
  lab(
    "hundred-square-studio",
    "4-1 4-2",
    "Hundred-Square Studio",
    "🟦",
    "Create a pixel design and describe the same shaded amount as a fraction, decimal, and percent.",
    "percent",
    "grid",
    [35, 100],
    [
      "Shade 35 out of 100 squares. Name the fraction, decimal, and percent.",
      "On paper, compare 0.4 and 4%. How many of 100 squares would each fill?",
      "Make a design representing three quarters. Explain all three notations.",
    ],
    "Design a two-color logo on a hundred grid. Label each color with an equivalent fraction, decimal, and percent, and prove that the whole design totals 100%.",
    "Pixel Passport",
  ),
  lab(
    "sale-signals",
    "4-3 4-4",
    "Sale Signals Studio",
    "🏷️",
    "Estimate a discount before finding its exact value. Decide whether the saving and final price on a sale sign make sense.",
    "percent",
    "discount",
    [25, 80],
    [
      "Find 10%, 25%, and 50% of the same price using benchmarks.",
      "Compare your estimate with the exact discount. Then find the remaining price.",
      "Explain why a 25% discount is not the same as subtracting $25 from every price.",
    ],
    "Create a truthful sale sign with original price, percent discount, dollars saved, and final price. Show a benchmark estimate and explain the calculation.",
    "Sale Sign Rescue",
  ),
  lab(
    "missing-whole",
    "4-5",
    "The Missing Whole Bureau",
    "🧩",
    "Recover a missing total from a known part and percent. Use the meaning of one percent to test your answer.",
    "percent",
    "whole",
    [30, 18],
    [
      "If 18 is 30%, find 10%, then 100%.",
      "Keep the part fixed and increase the percent. Predict whether the whole gets larger or smaller.",
      "Check a recovered whole by multiplying it by the given percent.",
    ],
    "Write a missing-total case with a known part and percent. Solve it two ways and explain why treating the part as the whole would fail.",
    "Total Recovery",
  ),
  lab(
    "shape-shift-garden",
    "5-1 5-2",
    "Shape-Shift Garden",
    "🌱",
    "Rearrange garden shapes to understand area. Track perpendicular height while you compare a parallelogram and a triangle.",
    "area",
    "triangle",
    [8, 6, 4],
    [
      "Compare a triangle and parallelogram with the same base and height.",
      "Change the base from 6 to 12 but keep height fixed. What happens to area?",
      "Explain why a slanted side cannot replace perpendicular height in the formula.",
    ],
    "Design one triangular and one parallelogram garden with equal area. Label bases and perpendicular heights and explain the factor of one half.",
    "Garden Mosaic",
  ),
  lab(
    "festival-floorplan",
    "5-3 5-4",
    "Festival Floorplan",
    "🎟️",
    "Plan a festival space made from trapezoids and smaller shapes. Decompose the floor plan so that no space is counted twice.",
    "area",
    "trapezoid",
    [10, 4, 6],
    [
      "Interpret the two parallel bases and the perpendicular height.",
      "Compare the trapezoid to a rectangle with the average base length.",
      "Split a composite floor plan into familiar shapes and explain how the areas combine.",
    ],
    "Sketch a festival floor with a trapezoid and a rectangle. Label enough measurements to find its area, then show a second valid decomposition.",
    "Floorplan Fit",
  ),
  lab(
    "packaging-workshop",
    "5-5 5-6",
    "Packaging Workshop",
    "📦",
    "Design a rectangular package, count its cubic capacity, and connect its three-dimensional form to a two-dimensional net.",
    "solid",
    "net",
    [4, 3, 2],
    [
      "Count one layer of cubes, then multiply by the number of layers.",
      "Match each pair of faces in the net. Which lengths meet when it folds?",
      "Make two boxes with the same volume but different dimensions.",
    ],
    "Design a package with volume 48 cubic units. Draw a labeled net and explain how its face dimensions match the box dimensions.",
    "Packing Puzzle",
  ),
  lab(
    "wrap-lab",
    "5-7 5-8",
    "Wrap Lab",
    "🎁",
    "Compare the covering needed for a prism and a square pyramid. Count every face once and distinguish slant height from vertical height.",
    "solid",
    "surface",
    [6, 4, 5],
    [
      "Find the areas of the three different face pairs on the prism.",
      "Switch to the square pyramid. Its third control is slant height; find each triangular face.",
      "Explain why volume would not tell you how much wrapping material is needed.",
    ],
    "Prepare a wrapping estimate for a prism and a square pyramid. Draw their faces, label dimensions, and justify the sum of face areas.",
    "Wrap-Off",
  ),
  lab(
    "polygon-pavilion",
    "5-9 5-10",
    "Polygon Pavilion",
    "🏛️",
    "Plan a polygon floor and a storage box for a pavilion. Separate square-unit floor coverage from cubic-unit storage capacity.",
    "area",
    "polygon",
    [4, 6, 3],
    [
      "Start with a square: four sides of length 6 and an apothem of 3. Find perimeter and area.",
      "Change the side count. The model computes the apothem; explain how congruent triangles build the area formula.",
      "Sketch a rectangular storage box and compare the units in its volume with the floor area units.",
    ],
    "Plan a regular-polygon floor using a stated perimeter and apothem, plus a rectangular storage box. Show both calculations and explain why their units differ.",
    "Pavilion Planner",
  ),
  lab(
    "fraction-food-truck",
    "6-1 6-2",
    "Fraction Food Truck",
    "🥣",
    "Measure servings from a supply of ingredients. Use fraction strips to see how many groups fit before using a division procedure.",
    "fraction",
    "servings",
    [3, 1, 2],
    [
      "Predict how many half-cup servings fit into three cups.",
      "Change the serving size to three quarters of a cup. Does the number of servings increase or decrease?",
      "Explain why dividing by a number smaller than one can increase the result.",
    ],
    "Design a food-truck recipe problem using a mixed-number supply and fractional serving size. Draw a strip model and check quotient × serving size = supply.",
    "Lunch Rush",
  ),
  lab(
    "power-plant",
    "6-3 6-4",
    "The Power Plant",
    "⚡",
    "Power a machine with numerical expressions. Distinguish repeated multiplication from multiplication by an exponent.",
    "power",
    "order",
    [3, 4, 2],
    [
      "Compare 3⁴ with 3 × 4. Expand the power to explain the difference.",
      "Predict 2 + 3⁴ before evaluating. Which operation comes first?",
      "Change the exponent by one and explain the multiplicative effect on the power.",
    ],
    "Build two numerical expressions using the same numbers but different grouping. Evaluate them step by step and explain why their values differ.",
    "Power Sequence",
  ),
  lab(
    "expression-remix",
    "6-5 6-6",
    "Expression Remix Studio",
    "🎛️",
    "Translate a situation into an expression, substitute values, and test whether two expressions stay equivalent.",
    "expression",
    "equivalence",
    [4, 3, 5],
    [
      "On paper, evaluate 4x + 3 when x = 5. Compare it with 4(x + 3) in the model. Why are the results different?",
      "Compare a(x + b) with ax + ab for several values.",
      "Explain why matching at only one value cannot prove two expressions equivalent.",
    ],
    "Write a situation for an algebraic expression. Give an equivalent expression, justify it with a property, and verify both at two different values.",
    "Remix Match",
  ),
  lab(
    "factor-factory",
    "6-7 6-8",
    "Factor Factory",
    "🏭",
    "Arrange products into equal rows. Use common factors to rewrite expressions and connect arrays to the distributive property.",
    "factors",
    "gcf",
    [18, 24],
    [
      "List every factor of each number. Which factors are shared?",
      "Use the greatest common factor to write 18 + 24 as a product.",
      "Explain why a common multiple and a common factor play different roles.",
    ],
    "Choose two whole numbers, build their factor lists, and rewrite their sum using the GCF. Show how an array proves the distributive form.",
    "Factory Sort",
  ),
  lab(
    "ribbon-rescue",
    "6-9 6-10",
    "Ribbon Rescue",
    "🎀",
    "Cut ribbons into fractional lengths. Decide how many pieces fit and distinguish a fractional quotient from the number of complete pieces.",
    "fraction",
    "ribbon",
    [5.5, 3, 4],
    [
      "How many 3/4-unit pieces fit into 5 1/2 units? Predict before checking.",
      "Separate the exact quotient from the number of complete pieces.",
      "Check the used length and remaining ribbon with multiplication and subtraction.",
    ],
    "Write a ribbon order with a mixed-number length and fractional piece size. Report the exact quotient, whole pieces, and remaining length with units.",
    "Ribbon Run",
  ),
  lab(
    "fraction-field-team",
    "6-11",
    "Fraction Field Team",
    "⛺",
    "Supply a field expedition with fractional quantities. Interpret the quotient in context and check whether the requested groups are possible.",
    "fraction",
    "field",
    [4.5, 2, 3],
    [
      "Find how many 2/3-liter portions fit into 4 1/2 liters.",
      "Explain the difference between the exact number of portions and full bottles you can fill.",
      "Create a problem where a quotient smaller than one makes sense.",
    ],
    "Plan a field-team supply using fraction division. Include a diagram, exact quotient, practical decision about complete groups, and a multiplication check.",
    "Supply Drop",
  ),
  lab(
    "synchronization-station",
    "6-12 6-13",
    "Synchronization Station",
    "🚦",
    "Synchronize repeating signals. Break numbers into prime factors and predict when two cycles next meet.",
    "factors",
    "lcm",
    [12, 18],
    [
      "List the first few multiples of each signal period.",
      "Use prime factors to explain the first shared positive multiple.",
      "Why is multiplying the two periods sometimes too large for the first meeting?",
    ],
    "Design two repeating signals with a common meeting time. Show prime factorizations and explain exactly why that meeting time is the least common multiple.",
    "Signal Sync",
  ),
  lab(
    "algebra-workshop",
    "6-14 6-15",
    "Algebra Workshop",
    "🛠️",
    "Unpack grouped expressions and combine matching terms. Build a visual proof that the simplified form preserves the value.",
    "expression",
    "distribute",
    [3, 4, 2],
    [
      "Expand 3(x + 4). Explain why both terms inside receive the factor 3.",
      "Compare the expanded and grouped forms at two values of x.",
      "Explain why 3x + 12 cannot be combined into 15x.",
    ],
    "Create an expression that needs both distribution and combining like terms. Show each legal step, then check the original and final forms at two values.",
    "Workshop Rebuild",
  ),
  lab(
    "elevation-expedition",
    "7-1 7-2",
    "Elevation Expedition",
    "🏔️",
    "Navigate above and below sea level. Represent signed measurements and use zero as a shared reference point.",
    "line",
    "opposites",
    [-4, 6],
    [
      "Place a location at −4. Where is its opposite?",
      "Try −2.5 and 2.5. Explain their equal distances from zero.",
      "Give a real situation where zero has a clear meaning.",
    ],
    "Draw an expedition profile with five signed elevations, including a non-integer. Label zero, choose an opposite pair, and explain the signs in context.",
    "Summit Signals",
  ),
  lab(
    "deep-sea-order",
    "7-3 7-4",
    "Deep Sea Dispatch",
    "🤿",
    "Order underwater locations and measure distance from sea level. Keep absolute value separate from greater-than comparisons.",
    "line",
    "absolute",
    [-7, -3],
    [
      "Which depth is greater, −7 or −3? Which is farther from zero?",
      "Find two different numbers with absolute value 6.",
      "Explain why the number with the greater absolute value is not always the greater number.",
    ],
    "Plan three underwater stops and one point above sea level. Order the elevations and separately rank their distances from sea level. Explain the difference.",
    "Depth Decoder",
  ),
  lab(
    "coordinate-couriers",
    "7-5 7-6",
    "Coordinate Couriers",
    "🚲",
    "Deliver parcels on a four-quadrant city grid. Use ordered pairs and calculate distances along horizontal or vertical streets.",
    "coordinates",
    "distance",
    [-3, 4, 2, 4],
    [
      "Move from A to B along their shared horizontal street. Find the distance.",
      "Put points on opposite sides of an axis with one coordinate shared.",
      "Explain why |x₂ − x₁| measures a horizontal distance and not every possible route.",
    ],
    "Design a delivery route with three axis-aligned segments. List every endpoint and segment distance, then calculate and justify the total route length.",
    "Courier Routes",
  ),
  lab(
    "grid-architects",
    "7-7 7-8",
    "Grid Architects",
    "🏗️",
    "Place a park in all four quadrants. Use coordinates to prove its side lengths, perimeter, and area.",
    "coordinates",
    "rectangle",
    [-4, -2, 3, 4],
    [
      "Use the two control points as opposite corners. Name the other corners.",
      "Find width and height from coordinate differences.",
      "Move the whole rectangle across an axis without changing its dimensions. What stays fixed?",
    ],
    "Design a rectangular park crossing both axes. List the four ordered pairs and prove its perimeter and area using coordinate distances.",
    "Park Builder",
  ),
  lab(
    "mirror-mission",
    "7-9",
    "Mirror Mission",
    "🪞",
    "Send a point through coordinate mirrors. Predict which coordinate changes and prove that reflected points stay equally far from the mirror.",
    "coordinates",
    "reflect",
    [-3, 4, 3, -4],
    [
      "Reflect (−3, 4) across the y-axis, then across the x-axis.",
      "Find a point that does not move when reflected across the x-axis.",
      "Explain why negating both coordinates is not a single reflection across one axis.",
    ],
    "Create a four-point emblem and reflect it across each axis. Give the image coordinates and explain how distance from the mirror proves your construction.",
    "Mirror Maze",
  ),
  lab(
    "balance-bureau",
    "8-1 8-2",
    "The Balance Bureau",
    "⚖️",
    "Test possible solutions and restore balance with inverse operations. Explain why the same operation belongs on both sides.",
    "balance",
    "add",
    [7, 19, 12],
    [
      "Test x = 12 in x + 7 = 19.",
      "Try a different candidate. Read the two side values and decide whether they balance.",
      "Explain how subtracting 7 from both sides preserves equality.",
    ],
    "Write an addition or subtraction equation for a real situation. Solve it, show equal operations on both sides, and verify by substitution.",
    "Balance Breakout",
  ),
  lab(
    "vault-division",
    "8-3",
    "Vault Division",
    "🔐",
    "Open evidence vaults by solving multiplication and division equations. A correct key must make the original equation true.",
    "balance",
    "multiply",
    [4, 36, 9],
    [
      "Test x = 9 in 4x = 36.",
      "On paper, compare 4x = 36 with x ÷ 4 = 9. Explain why their solutions differ.",
      "On paper, build an equation with a decimal coefficient and a whole-number solution.",
    ],
    "Design a two-vault puzzle: one multiplication equation and one division equation. Show inverse operations and verify both keys by substitution.",
    "Vault Sequence",
  ),
  lab(
    "entry-rules",
    "8-4 8-5",
    "Entry Rules Arcade",
    "🎫",
    "Write fair entry rules for an arcade. Use inequality symbols and decide whether a boundary value is allowed.",
    "inequality",
    "entry",
    [12, 10],
    [
      "Compare x > 12 with x ≥ 12. Test the boundary value itself.",
      "Show several different values that satisfy one rule.",
      "Explain why an inequality usually has many solutions rather than one.",
    ],
    "Write two entry rules: one includes its boundary and one excludes it. Give words, symbols, number-line graphs, and examples and nonexamples for each.",
    "Gatekeeper",
  ),
  lab(
    "budget-boundaries",
    "8-6 8-7",
    "Budget Boundaries",
    "💼",
    "Plan a purchase with a limit. Solve an inequality, graph its solutions, and select a sensible whole-number decision.",
    "inequality",
    "budget",
    [15, 6],
    [
      "Interpret x ≤ 15 as a budget limit. Does spending exactly 15 qualify?",
      "If each ticket costs $3 and you have $15, write and solve 3t ≤ 15.",
      "Distinguish an equation asking for an exact cost from an inequality setting a maximum.",
    ],
    "Plan an event under a fixed budget. Write an inequality, solve and graph it, then explain why the practical ticket count must be a whole number.",
    "Budget Quest",
  ),
  lab(
    "variable-weather",
    "9-1 9-2",
    "Variable Weather Station",
    "🌦️",
    "Connect changing quantities through a table and graph. Explain what each variable means and how one responds to the other.",
    "growth",
    "weather",
    [2, 4, 3],
    [
      "For a tank starting with 4 liters and filling at 2 liters per minute, predict the amount after 3 minutes.",
      "Identify the independent variable and the dependent variable.",
      "Explain what the graph’s starting value and rate of change mean in context.",
    ],
    "Design a measurement story with two variables. Give a labeled table and graph, explain the starting value, and describe how the quantities change together.",
    "Forecast Route",
  ),
  lab(
    "function-food-fair",
    "9-3 9-4",
    "Function Food Fair",
    "🍿",
    "Compare fair-booth plans with starting fees and per-item costs. Write equations and use them to make a decision.",
    "growth",
    "fees",
    [3, 5, 4],
    [
      "Interpret C = 3n + 5. What does each number mean?",
      "Compare with C = 4n + 1 at n = 1, 4, and 7.",
      "Find when the plans cost the same and explain why the cheaper plan can change.",
    ],
    "Create two booth pricing plans. Show equations and a table, find a point where costs match if one exists, and recommend a plan for a stated number of items.",
    "Fairground Face-Off",
  ),
  lab(
    "symmetry-safari",
    "10-1 10-2",
    "Symmetry Safari",
    "🦋",
    "Look for mathematical structure in nature and design. Test symmetry with evidence and connect observations to a precise representation.",
    "coordinates",
    "symmetry",
    [-4, 3, 4, 3],
    [
      "Plot mirror partners on either side of the y-axis.",
      "Add a point on the mirror line. Why does its reflection stay in place?",
      "Explain the difference between an ideal symmetric model and an almost-symmetric natural object.",
    ],
    "Design an emblem inspired by nature. Give at least three mirror pairs on a coordinate grid and explain where its symmetry is exact and where a real example may differ.",
    "Safari Match",
  ),
  lab(
    "invention-playground",
    "10-3 10-4",
    "Invention Playground",
    "💡",
    "Use playful constraints to invent a solution. Build, test, compare strategies, and improve a design with mathematical evidence.",
    "array",
    "design",
    [6, 4],
    [
      "Build different rectangles with area 24. Which uses the least perimeter?",
      "Predict before checking a new design.",
      "Explain how a useful constraint can lead to more creative solutions.",
    ],
    "Invent a rectangular tabletop game board with 24 spaces. Compare two layouts, choose one, and justify the design with area, perimeter, and how players will use it.",
    "Inventors Challenge",
  ),
  lab(
    "my-math-next",
    "10-5 10-6",
    "My Math, Next",
    "🚀",
    "Explore a pattern beyond the first few cases and tell the story of your mathematical growth. Make a claim, test it, and name your next question.",
    "growth",
    "future",
    [4, 1, 5],
    [
      "Use the first few stages to predict stage 20.",
      "Write a rule that can describe any stage. What does that let you do?",
      "Find two different strategies and explain when each is useful.",
    ],
    "Build a mini-exhibit of a pattern and your thinking. Include an early attempt, a revision, a general rule, and one question you would like to investigate next.",
    "Next Frontier",
  ),
];

export const unitNames = [
  "Math Is…",
  "Statistics",
  "Ratios & Rates",
  "Percents",
  "Area, Surface Area & Volume",
  "Expressions",
  "Integers & the Coordinate Plane",
  "Equations & Inequalities",
  "Two-Variable Relationships",
  "Math Is…",
];
