name = "focus-school"
pages_build_output_dir = "."
compatibility_date = "2026-05-25"

# Cloud sync KV Namespace binding for the Focus School planner
[[kv_namespaces]]
binding = "NOAM_SCHOOL_KV"
id = "59075911253f400f807345430425946c"
