// Every finale has authored places and a concrete outcome. No student data lives here.
const worlds = {
  'algebra-workshop': ['factory', 'Rebuild the inventor’s workshop', 'Parts lift|Assembly arm|Launch press', 'Restore the machine by making its expression produce the requested output.'],
  'balance-bureau': ['citadel', 'Open the three balance gates', 'Outer gate|Counterweight bridge|Archive door', 'Find the value that keeps both sides balanced to open a gate.'],
  'best-buy-boulevard': ['city', 'Stock the neighborhood supply depot', 'Corner store|Market hall|Supply depot', 'Set the unit price so the supply team can compare offers fairly.'],
  'budget-boundaries': ['city', 'Plan a journey within the budget', 'Ticket booth|Supply store|Expedition dock', 'Test which values fit the rule before the crew commits its supplies.'],
  'consistency-cup': ['observatory', 'Tune the precision team', 'Training ground|Signal tower|Final arena', 'Adjust an observation to hit the requested measure of consistency.'],
  'coordinate-couriers': ['city', 'Reconnect the courier network', 'Canal crossing|Rooftop depot|Central station', 'Position the route endpoint using the coordinate grid.'],
  'data-newsroom': ['city', 'Restore the city news signal', 'Field station|News desk|Broadcast mast', 'Repair the data display so the newsroom can report an accurate measure.'],
  'decimal-design-shop': ['factory', 'Finish the design district’s orders', 'Fabric stall|Print studio|Exhibition hall', 'Adjust the order to make the receipt total match the commission.'],
  'deep-sea-order': ['ocean', 'Recover the deep-sea research stations', 'Kelp station|Reef station|Trench beacon', 'Place the research equipment at the requested signed-number relationship.'],
  'delivery-dispatch': ['city', 'Deliver supplies to three districts', 'River depot|Hill depot|Central depot', 'Adjust the supply amount to make the required number of equal shipments.'],
  'elevation-expedition': ['mountain', 'Reconnect the summit rescue route', 'Valley camp|Ridge shelter|Summit signal', 'Use signed positions to calibrate each rescue marker.'],
  'entry-rules': ['citadel', 'Become the gatekeeper', 'Garden gate|Tower gate|Festival gate', 'Test the boundary and admit only values that satisfy the requested condition.'],
  'expression-remix': ['observatory', 'Bring the music station back online', 'Sampler|Mixing desk|Main stage', 'Tune an expression until the signal reaches the requested output.'],
  'factor-factory': ['factory', 'Restart the factor factory', 'Sorting belt|Gear room|Power core', 'Use common factors or multiples to align each machine’s settings.'],
  'fair-share-festival': ['city', 'Prepare a fair festival', 'Snack stand|Game tent|Festival square', 'Adjust the data and meet the target before opening the next festival area.'],
  'festival-floorplan': ['city', 'Build the festival grounds', 'Welcome tent|Workshop tent|Main pavilion', 'Set the shape dimensions so each area fits the building plan.'],
  'fraction-field-team': ['mountain', 'Resupply the field team', 'Trail camp|Survey camp|Peak camp', 'Divide the available supplies into the required number of equal servings.'],
  'fraction-food-truck': ['city', 'Take the food truck across town', 'Riverside stop|Garden stop|Night market', 'Match the number of servings to the order before the truck moves on.'],
  'function-food-fair': ['city', 'Open the function food fair', 'Breakfast stall|Lunch stall|Celebration stall', 'Use the input-output rule to meet each stall’s production target.'],
  'grid-architects': ['city', 'Design a connected city park', 'Playground|Community garden|Park overlook', 'Place points carefully to satisfy the coordinate plan.'],
  'hundred-square-studio': ['observatory', 'Illuminate the pixel exhibition', 'Color wall|Mosaic hall|Sky display', 'Use the hundred square to match each artwork’s percentage commission.'],
  'invention-playground': ['factory', 'Build a playground of inventions', 'Climbing frame|Puzzle floor|Inventors stage', 'Arrange rows and columns to supply the exact number of spaces.'],
  'math-detectives': ['city', 'Follow the missing-pattern trail', 'Corner clue|Courtyard clue|Archive clue', 'Construct an array that verifies each clue with mathematical evidence.'],
  'middle-ground': ['observatory', 'Recover the observatory signals', 'Ground receiver|Dish array|Sky observatory', 'Adjust an observation until the center of the data matches the signal target.'],
  'mirror-mission': ['citadel', 'Navigate the mirror citadel', 'Mirror hall|Reflection bridge|Crystal chamber', 'Reflect the point across the stated axis to align each passage.'],
  'missing-whole': ['citadel', 'Recover the lost totals', 'Ledger vault|Survey archive|Grand treasury', 'Use a known part and percent to recover each missing whole.'],
  'mixture-matchup': ['factory', 'Restore the city’s colors', 'Paint lab|Mural wall|Color fountain', 'Balance the color mixture to match the commissioned ratio.'],
  'my-math-next': ['observatory', 'Chart the next frontier', 'Launch platform|Orbit station|Far beacon', 'Apply the growth rule to reach each new signal target.'],
  'neighborhood-makers': ['city', 'Build the makers market', 'Craft stall|Design stall|Market square', 'Set decimal prices and quantities to complete each maker’s order.'],
  'outlier-investigation': ['observatory', 'Investigate the unusual signal', 'Sensor field|Evidence room|Signal archive', 'Use the data model to test how a changed observation affects the center.'],
  'packaging-workshop': ['factory', 'Prepare the expedition cargo', 'Packing bench|Loading bay|Cargo airship', 'Build a solid whose dimensions match the requested measure.'],
  'pattern-studio': ['observatory', 'Restore the pattern relay', 'First relay|Hill relay|Sky relay', 'Use a growth rule to synchronize each relay’s output.'],
  'polygon-pavilion': ['city', 'Raise the polygon pavilion', 'Garden shelter|Courtyard roof|Grand pavilion', 'Adjust the polygon to meet the architect’s area target.'],
  'power-plant': ['factory', 'Bring the power grid online', 'Generator|Substation|City beacon', 'Evaluate powers in the correct order to tune each output.'],
  'ratio-railway': ['mountain', 'Reopen the mountain railway', 'Valley station|Viaduct station|Summit station', 'Use the proportional relationship to plan the train’s capacity.'],
  'recipe-remix': ['factory', 'Broadcast three perfect recipe mixes', 'Juice bar|Tasting kitchen|Radio kitchen', 'Scale both ingredients consistently to match the requested mixture.'],
  'ribbon-rescue': ['city', 'Restore the celebration decorations', 'Street arch|Garden arch|Festival arch', 'Cut equal fractional lengths to meet each decoration order.'],
  'sale-signals': ['city', 'Repair the market’s sale signs', 'Book stall|Supply stall|Market entrance', 'Use the percent model to verify each advertised deal.'],
  'scale-and-sail': ['ocean', 'Launch the harbor fleet', 'Chart room|Boat yard|Harbor light', 'Convert lengths using an exact factor before fitting each part.'],
  'shape-shift-garden': ['mountain', 'Grow the geometric garden', 'Seed terrace|Flower terrace|Garden lookout', 'Change dimensions to build garden plots with the requested area.'],
  'symmetry-safari': ['mountain', 'Trace the symmetry trail', 'River marker|Canopy marker|Lookout marker', 'Reflect each survey point to complete the symmetric trail.'],
  'synchronization-station': ['factory', 'Synchronize the station network', 'Clock tower|Switch room|Central signal', 'Find settings whose common factors or multiples align the network.'],
  'variable-weather': ['observatory', 'Reconnect the weather stations', 'Coast sensor|Hill sensor|Cloud observatory', 'Choose the input that gives the forecast model its target output.'],
  'vault-division': ['citadel', 'Unlock the divided vault', 'Entry lock|Gear lock|Core lock', 'Use an inverse operation to balance the vault’s equation.'],
  'world-expedition': ['mountain', 'Equip the border-crossing expedition', 'Map cabin|Border camp|Summit outpost', 'Convert measurements accurately so the equipment fits at each outpost.'],
  'wrap-lab': ['factory', 'Wrap the expedition’s fragile cargo', 'Sample crate|Instrument crate|Flagship crate', 'Set dimensions to match the surface-area requirement.'],
};
export const expeditionWorlds = Object.fromEntries(Object.entries(worlds).map(([id, [theme, goal, locations, brief]]) => [id, { theme, goal, locations: locations.split('|'), brief }]));
