#!/usr/bin/env node
/**
 * One-off warmup injector. Warmups are NOT regenerated by the build —
 * lesson configs are the source of truth once written (see
 * scripts/soften-unit1-warmups.mjs). This file must still be safe to run:
 * a stale hardcoded lesson list previously omitted 23 whole-group lessons
 * that exist on disk and named 7 that do not, so a re-run would have
 * pointed those warmups at the wrong previous lesson (or at themselves).
 *
 * Sequence is derived from whole-group folders on disk, sorted by unit then
 * lesson number — Reveal Math order inside the book, not district pacing
 * order. District pacing is the wrong previous-lesson for a warmup: Unit 5
 * still reviews 5-7 before 5-8 even when the district teaches Unit 5 in spring.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANK_PATH = join(ROOT, "spiral-review", "bank.json");
const LESSONS_DIR = join(ROOT, "lessons");

/** Whole-group lesson ids that actually exist on disk, in book order. */
export function wholeGroupLessonIds(lessonsDir = LESSONS_DIR) {
  return readdirSync(lessonsDir)
    .filter((d) => existsSync(join(lessonsDir, d, "config.json")) && /^\d+-\d+$/.test(d))
    .sort((a, b) => {
      const [au, al] = a.split("-").map(Number);
      const [bu, bl] = b.split("-").map(Number);
      return au - bu || al - bl;
    });
}

export function previousLessonId(ids, baseId) {
  const idx = ids.indexOf(baseId);
  if (idx > 0) return ids[idx - 1];
  return baseId;
}

export function getBaseLessonId(folderName) {
  const m = String(folderName).match(/^(\d+-\d+)/);
  return m ? m[1] : folderName;
}

function pickWarmupQuestions(questionsByLesson, questions, prevLessonId, currentLessonId) {
  const pool = questionsByLesson[prevLessonId] || questionsByLesson[currentLessonId] || questions;
  let candidates = pool.filter((q) => q.tier === "approaching" || q.tier === "on-level");
  if (candidates.length < 3) candidates = pool;

  let seed = 0;
  for (let i = 0; i < currentLessonId.length; i++) seed += currentLessonId.charCodeAt(i);

  const picked = [];
  const cloned = [...candidates];
  const count = seed % 2 === 0 ? 3 : 4;
  while (picked.length < count && cloned.length > 0) {
    const idx = (seed + picked.length * 7) % cloned.length;
    const q = cloned.splice(idx, 1)[0];
    picked.push({
      id: `warmup-${currentLessonId}-${picked.length + 1}`,
      stem: q.stem,
      choices: q.choices,
      correctIndex: q.correctIndex,
      explanation: q.explanation || "Review previous lesson concept.",
    });
  }
  return picked;
}

function generate() {
  const bank = JSON.parse(readFileSync(BANK_PATH, "utf8"));
  const questions = bank.questions;
  const questionsByLesson = {};
  for (const q of questions) {
    if (!q.lessonId) continue;
    if (!questionsByLesson[q.lessonId]) questionsByLesson[q.lessonId] = [];
    questionsByLesson[q.lessonId].push(q);
  }

  const ids = wholeGroupLessonIds(LESSONS_DIR);
  let countUpdated = 0;

  for (const dirName of readdirSync(LESSONS_DIR)) {
    const configPath = join(LESSONS_DIR, dirName, "config.json");
    if (!existsSync(configPath)) continue;

    try {
      const cfg = JSON.parse(readFileSync(configPath, "utf8"));
      const baseId = getBaseLessonId(dirName);
      const prevId = previousLessonId(ids, baseId);

      let prevTitle = `Lesson ${prevId}`;
      const prevConfigPath = join(LESSONS_DIR, prevId, "config.json");
      if (existsSync(prevConfigPath)) {
        const prevCfg = JSON.parse(readFileSync(prevConfigPath, "utf8"));
        if (prevCfg.title) prevTitle = prevCfg.title;
      }

      cfg.warmup = {
        title: "Warmup: Previous Lesson Check",
        prevLessonId: prevId,
        prevLessonTitle: prevTitle,
        questions: pickWarmupQuestions(questionsByLesson, questions, prevId, baseId),
      };

      writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n");
      countUpdated++;
    } catch (err) {
      console.error(`Error updating ${configPath}:`, err.message);
    }
  }

  console.log(
    `Successfully generated and injected 3-4 autograded Warmup questions into ${countUpdated} lesson configs!`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) generate();
