#!/usr/bin/env node
/**
 * Warmup injector. Warmups are NOT regenerated by the build — lesson configs are
 * the source of truth once written (see scripts/soften-unit1-warmups.mjs). This
 * file must still be safe to run, because two earlier versions of it were not:
 * a stale hardcoded lesson list omitted 23 lessons that exist on disk, and the
 * sequence it did use was BOOK ORDER.
 *
 * BOOK ORDER IS THE WRONG PREVIOUS LESSON. This file used to argue the opposite
 * in this comment — "District pacing is the wrong previous-lesson for a warmup:
 * Unit 5 still reviews 5-7 before 5-8 even when the district teaches Unit 5 in
 * spring." Inside a unit that reasoning holds, and it is why the instructional
 * sequence keeps each unit's own order. Across units it fails outright: the
 * Pre-Unit is assembled from 1-1, 2-6, 2-7, 6-1 and 6-2, so book order made
 * 2-6's warmup review 2-5 (interquartile range) and 6-1's review 5-10 (volume),
 * neither of which any student had met. Two lessons on either side of a unit
 * boundary are a day apart in the classroom and months apart in the book.
 *
 * The sequence therefore comes from shared/curriculum/instructional-sequence.js,
 * the same derivation the Teach picker, the planner and the warmup gates use.
 *
 * Variants (small group, catch-up) INHERIT their parent's warmup rather than
 * authoring their own. 197 independent copies had drifted; 94 of them named a
 * lesson taught later, a title that was not that lesson's title, or both.
 *
 * Default is --check (report-only). Pass --write to mutate.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  baseLessonId,
  buildInstructionalSequence,
  getPreviousTaughtLesson,
} from "../shared/curriculum/instructional-sequence.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BANK_PATH = join(ROOT, "spiral-review", "bank.json");
const LESSONS_DIR = join(ROOT, "lessons");
const readJson = (p) => JSON.parse(readFileSync(p, "utf8"));

/** Re-exported under its established name so callers keep working. */
export const getBaseLessonId = baseLessonId;

/** The canonical instructional sequence, built from the live pacing data. */
export function instructionalSequence(root = ROOT) {
  return buildInstructionalSequence({
    ranges: readJson(join(root, "data/pacing-unit-ranges.json")),
    authored: readJson(join(root, "data/pacing-unit-lessons.json")),
    manifest: readJson(join(root, "data/curriculum-launch-manifest.json")),
  });
}

/**
 * The lesson taught immediately before `baseId`.
 *
 * Returns null for the first lesson of the course and for anything outside the
 * sequence. A null must NEVER be filled in with arithmetic on the id: the whole
 * defect class this file exists to prevent is exactly that fallback. The old
 * signature returned `baseId` itself in that case, which made 5-8's warmup
 * review 5-8.
 */
export function previousTaughtLesson(baseId, sequence) {
  return getPreviousTaughtLesson(baseId, sequence);
}

function pickWarmupQuestions(questionsByLesson, questions, prevLessonId, currentLessonId) {
  const pool = questionsByLesson[prevLessonId] || questionsByLesson[currentLessonId] || questions;
  let candidates = pool.filter((q) => q.tier === "approaching" || q.tier === "on-level");
  if (candidates.length < 3) candidates = pool;

  let seed = 0;
  for (let i = 0; i < currentLessonId.length; i++) seed += currentLessonId.charCodeAt(i);

  const picked = [];
  const cloned = [...candidates];
  const count = seed % 2 === 0 ? 3 : 4;
  while (picked.length < count && cloned.length > 0) {
    const idx = (seed + picked.length * 7) % cloned.length;
    const q = cloned.splice(idx, 1)[0];
    picked.push({
      id: `warmup-${currentLessonId}-${picked.length + 1}`,
      stem: q.stem,
      choices: q.choices,
      correctIndex: q.correctIndex,
      explanation: q.explanation || "Review previous lesson concept.",
    });
  }
  return picked;
}

/**
 * Plan (and optionally write) warmup blocks.
 *
 * Default is report-only. Warmups on disk are authored source of truth, so a
 * bare run tells you what would change and touches nothing.
 */
export function generate({
  write = false,
  lessonsDir = LESSONS_DIR,
  bankPath = BANK_PATH,
  sequence = null,
  titles = null,
} = {}) {
  const bank = JSON.parse(readFileSync(bankPath, "utf8"));
  const questions = bank.questions;
  const questionsByLesson = {};
  for (const q of questions) {
    if (!q.lessonId) continue;
    (questionsByLesson[q.lessonId] = questionsByLesson[q.lessonId] || []).push(q);
  }

  const seq = sequence || instructionalSequence();
  const titleOf = (id) => {
    if (titles) return titles[id] || `Lesson ${id}`;
    const p = join(lessonsDir, id, "config.json");
    return (existsSync(p) && readJson(p).title) || `Lesson ${id}`;
  };

  const folders = readdirSync(lessonsDir).filter((d) =>
    existsSync(join(lessonsDir, d, "config.json")),
  );

  /* Core lessons first: a variant copies its parent's finished warmup, so the
   * parent has to be settled before the variant is read. */
  const cores = folders.filter((d) => baseLessonId(d) === d);
  const variants = folders.filter((d) => baseLessonId(d) !== d);
  const proposals = new Map();

  for (const id of cores) {
    const prevId = previousTaughtLesson(id, seq);
    if (prevId === null) {
      /* No previous taught lesson. The honest shape is prerequisite retrieval
       * naming a SKILL — never an invented lesson id, and never this lesson. */
      const existing = readJson(join(lessonsDir, id, "config.json")).warmup;
      proposals.set(id, existing || null);
      continue;
    }
    proposals.set(id, {
      title: "Warmup: Previous Lesson Check",
      reviews: prevId,
      prevLessonId: prevId,
      prevLessonTitle: titleOf(prevId),
      questions: pickWarmupQuestions(questionsByLesson, questions, prevId, id),
    });
  }

  for (const id of variants) {
    const parent = proposals.get(baseLessonId(id));
    if (!parent) continue;
    proposals.set(id, {
      ...parent,
      questions: parent.questions.map((q, i) => ({ ...q, id: `warmup-${id}-${i + 1}` })),
    });
  }

  let countUpdated = 0;
  let wouldChange = 0;
  for (const [id, proposed] of proposals) {
    if (!proposed) continue;
    const configPath = join(lessonsDir, id, "config.json");
    const cfg = readJson(configPath);
    if (JSON.stringify(cfg.warmup || null) !== JSON.stringify(proposed)) wouldChange++;
    if (!write) continue;
    cfg.warmup = proposed;
    writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n");
    countUpdated++;
  }

  if (!write) {
    console.log(
      `--check: generator would rewrite warmup on ${wouldChange} config(s). ` +
        "Pass --write to mutate. On-disk warmups are the source of truth.",
    );
    return { wouldChange, countUpdated: 0, wrote: false };
  }
  console.log(`Injected warmups into ${countUpdated} lesson configs.`);
  return { wouldChange, countUpdated, wrote: true };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  generate({ write: process.argv.includes("--write") });
}
