#!/usr/bin/env node
/* ==========================================================================
 * generated-pages-fresh.test.mjs — a committed lesson page must still match
 * the config.json it was generated from.
 *
 * WHY THIS EXISTS
 *
 * lessons/<id>/*.html are a SECOND copy of the lesson's content. Editing a
 * config changes the interactive lesson immediately and changes these pages
 * NEVER, so they rot silently: the page renders, looks right, and quietly
 * teaches something the curriculum no longer says.
 *
 * On 2026-08-01 the first clean full-fleet regeneration found 287 pages that
 * had rotted exactly this way — 215 worksheets whose word banks were missing
 * the lesson-title vocabulary term and whose error-analysis notes were missing
 * the diagnostic half of the correction, and 72 handouts whose vocabulary
 * tables omitted the title term outright.
 *
 * WHY IT COMPARES OUTPUT, NOT TEXT
 *
 * The obvious check — grep the page for a field's text from config.json — is
 * NOT a sound invariant here, and I built it first and threw it away:
 *   - slides.html renders `commonMistake` REWORDED, not verbatim;
 *   - learn.html renders Notice & Wonder CONDITIONALLY (present in 1-4,
 *     absent in 1-1);
 *   - a naive presence check flagged 74 lessons that were perfectly in sync.
 * Comparing against the generator's own output has none of that ambiguity, and
 * it covers every field at once instead of a hand-listed few. Injected sentinel
 * blocks are excluded by construction, because `isGeneratedFresh` re-splices
 * the ones already on disk before comparing.
 *
 * SCOPE. Wired for the generators where this has actually bitten. The remaining
 * lesson-page generators can be added the same way (a `--check` flag delegating
 * to `isGeneratedFresh`) once each is confirmed idempotent across the fleet.
 *
 * learn.html was added on 2026-08-12, and the reason is worth recording. The
 * C1 wave rewrote seven lessons' Build-the-Idea worked examples. Every gate in
 * the repo went green — full `npm run validate`, 159 test scripts, es-parity —
 * while https://eduwonderlab.com/lessons/1-1/learn.html still served the old
 * text, because learn.html is generated by scripts/generate-notes.mjs and
 * NOTHING checked it. Only opening the page in a browser caught it. That is
 * precisely the rot this file exists to prevent, on a page type it did not yet
 * cover.
 *
 * COVERAGE, and why it is now every committed lesson page.
 *
 * The rule that decides what belongs here is not "is it important" — it is
 * "can it drift". A page rots only if it is BOTH a committed second copy of the
 * config AND absent from `npm run build`. printable.html is deliberately not
 * listed: generate-printable-lesson.mjs runs inside `npm run build`, so every
 * deploy rebuilds it and it cannot go stale. Everything else that a student or
 * teacher can open is here.
 *
 * The rule is about drift, not about lessons, so it reaches past lesson pages.
 * mstar-practice/ was added on 2026-09-02: those unit practice tests are a
 * committed second copy of the lessons' authored `mstarPractice` items and are
 * absent from `npm run build`, which is the same pair of conditions. Edit an
 * item and the lesson asks the new question immediately while the practice
 * test — and the SCORM package pointing at it — would serve the old one
 * forever. Its answer keys and hub are generated from the same run and are
 * checked with it.
 *
 * Each generator was confirmed DETERMINISTIC before being made a hard gate:
 * run twice from a clean tree, byte-identical output both times, and running it
 * again over its own output changes nothing. A non-deterministic generator
 * would have to be report-only, because a gate that flips on a timestamp
 * teaches people to ignore it. None of these are.
 *
 * generate-notes.mjs owns four page types and takes `--pages` to select them;
 * all four are gated. The others take a plain `--check`.
 * ========================================================================== */

import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const GENERATORS = [
  [
    "worksheet.html, worksheet-answer-key.html, worksheet-2.html, worksheet-2-answer-key.html",
    "../scripts/generate-worksheets.mjs",
    [],
  ],
  ["practice.html, practice-answer-key.html", "../scripts/generate-sg-practice.mjs", []],
  ["handout.html", "../scripts/generate-handout-html.mjs", []],
  [
    "notes.html, notes-teacher.html, learn.html, vocab.html",
    "../scripts/generate-notes.mjs",
    ["--pages", "notes.html,notes-teacher.html,learn.html,vocab.html"],
  ],
  ["slides.html", "../scripts/generate-slides.mjs", []],
  ["homework.html", "../scripts/generate-homework-html.mjs", []],
  ["editable-slides.html", "../scripts/generate-editable-slides-page.mjs", []],
  [
    "mstar-practice/ (unit practice tests + answer keys + hub)",
    "../scripts/generate-mstar-practice.mjs",
    [],
  ],
  [
    "mstar-worksheet.html, mstar-worksheet-answer-key.html",
    "../scripts/generate-mstar-worksheets.mjs",
    [],
  ],
];

const stale = [];
for (const [page, rel, extraArgs] of GENERATORS) {
  const script = fileURLToPath(new URL(rel, import.meta.url));
  try {
    execFileSync(process.execPath, [script, "--check", ...extraArgs], { stdio: "pipe" });
  } catch (err) {
    const detail = `${err.stderr ?? ""}`.trim() || `${err.stdout ?? ""}`.trim();
    stale.push(`${page}:\n${detail}`);
  }
}

assert.deepEqual(
  stale,
  [],
  `Generated page(s) no longer match the config.json they were built from:\n\n${stale.join("\n\n")}`,
);

console.log(`Generated pages fresh: ${GENERATORS.map(([p]) => p).join(", ")} match their configs.`);
