#!/usr/bin/env node
/* =============================================================================
 * generate-warmups.test.mjs — the lesson sequence must come from disk.
 * -----------------------------------------------------------------------------
 * scripts/generate-warmups.mjs used to carry a hardcoded ALL_LESSON_IDS of 68
 * ids. The tree has 84 whole-group lessons; 23 on disk were missing from the
 * list and 7 in the list were gone (1-7, 4-6..4-9, 9-5, 9-6). For any id not
 * in the list, getPrevLessonId fell through to "return baseId", so a re-run
 * would have made 5-8's warmup review 5-8.
 *
 * Warmups are not regenerated by the build, so this did not corrupt the
 * current configs by itself. It is a landmine: the next person who runs the
 * generator would write the wrong previous lesson into every omitted config.
 *
 * The SECOND landmine was the ordering itself. The generator derived "previous
 * lesson" from the on-disk folders sorted by (unit, lesson) — book order. The
 * district does not teach in book order, and its Pre-Unit is assembled from
 * 1-1, 2-6, 2-7, 6-1, 6-2, so a re-run would have written "2-6 reviews 2-5" and
 * "6-1 reviews 5-10". Both name lessons students meet months later. The
 * sequence now comes from shared/curriculum/instructional-sequence.js, and the
 * assertions below pin that it does.
 * ============================================================================= */
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  generate,
  getBaseLessonId,
  instructionalSequence,
  previousTaughtLesson,
} from "../scripts/generate-warmups.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LESSONS = join(ROOT, "lessons");
const SRC = readFileSync(join(ROOT, "scripts/generate-warmups.mjs"), "utf8");

test("importing the generator does not write lesson configs", () => {
  // If the write loop still ran at module load, this file could not import it
  // without mutating the curriculum. The assertion is the import itself.
  assert.ok(typeof instructionalSequence === "function");
});

test("the generator does not keep a hardcoded lesson-id array", () => {
  assert.doesNotMatch(
    SRC,
    /ALL_LESSON_IDS\s*=\s*\[/,
    "stale hardcoded ALL_LESSON_IDS is how 23 lessons would review themselves",
  );
  assert.match(
    SRC,
    /includes\("--write"\)/,
    "a bare run must not write; --write is the mutate switch",
  );
});

test("the sequence covers every whole-group lesson on disk, exactly once", () => {
  const fromDisk = readdirSync(LESSONS)
    .filter((d) => existsSync(join(LESSONS, d, "config.json")) && /^\d+-\d+$/.test(d))
    .sort();
  const sequenced = [...instructionalSequence().order].sort();
  assert.deepEqual(sequenced, fromDisk);
  assert.ok(fromDisk.length >= 80, `expected a full Grade 6 set, found ${fromDisk.length}`);
  assert.ok(fromDisk.includes("5-8"), "5-8 exists on disk and must be in the sequence");
  assert.ok(fromDisk.includes("6-13"), "6-13 exists on disk and must be in the sequence");
  assert.ok(!fromDisk.includes("4-9"), "4-9 was removed; a hardcoded list still named it");
});

test("the generator derives previous lessons from the instructional sequence", () => {
  assert.doesNotMatch(
    SRC,
    /\.sort\(\s*\(a,\s*b\)\s*=>\s*\{[\s\S]*?au\s*-\s*bu/,
    "sorting folders by (unit, lesson) is book order, which is not the teaching order",
  );
  assert.match(
    SRC,
    /instructional-sequence\.js/,
    "the generator must read the canonical sequence, not build a second one",
  );
  const seq = instructionalSequence();
  // The regression case, asserted through the generator's own export.
  assert.equal(previousTaughtLesson("2-6", seq), "1-1");
  assert.equal(previousTaughtLesson("6-1", seq), "2-7");
  assert.equal(previousTaughtLesson("5-1", seq), "9-4");
});

test("a lesson with no previous taught lesson returns null, never itself", () => {
  const seq = instructionalSequence();
  assert.equal(previousTaughtLesson(seq.order[0], seq), null);
  assert.notEqual(previousTaughtLesson("5-8", seq), "5-8");
  assert.equal(previousTaughtLesson("not-a-lesson", seq), null);
});

test("variant folders still map to their whole-group id", () => {
  assert.equal(getBaseLessonId("5-8-group1"), "5-8");
  assert.equal(getBaseLessonId("10-1-catchup"), "10-1");
  assert.equal(getBaseLessonId("2-12"), "2-12");
});

test("variant warmups are their parent's warmup, not a second copy", () => {
  // 197 independently authored variant warmups had drifted: 25 named a lesson
  // taught AFTER the variant's parent and 91 printed a title that was not the
  // named lesson's title. Equality with the parent is the rule that removes the
  // whole class of defect rather than fixing instances of it.
  const strip = (w) =>
    JSON.stringify({ ...w, questions: w.questions.map(({ id: _i, ...q }) => q) });
  for (const id of ["2-5-catchup", "3-8-catchup", "6-3-group1", "2-6-group2"]) {
    const variant = JSON.parse(readFileSync(join(LESSONS, id, "config.json"), "utf8")).warmup;
    const parent = JSON.parse(
      readFileSync(join(LESSONS, getBaseLessonId(id), "config.json"), "utf8"),
    ).warmup;
    assert.equal(strip(variant), strip(parent), `${id} has drifted from ${getBaseLessonId(id)}`);
  }
});

test("without --write the generator reports drift and does not mutate", () => {
  const dir = mkdtempSync(join(tmpdir(), "neft-warmup-"));
  mkdirSync(join(dir, "1-1"));
  mkdirSync(join(dir, "2-6"));
  writeFileSync(
    join(dir, "1-1", "config.json"),
    JSON.stringify({ title: "Math is Mine", warmup: { kind: "spiral", spiralFrom: "x" } }) + "\n",
  );
  writeFileSync(join(dir, "2-6", "config.json"), JSON.stringify({ title: "Divide" }) + "\n");
  const bankPath = join(dir, "bank.json");
  writeFileSync(
    bankPath,
    JSON.stringify({
      questions: [
        {
          lessonId: "1-1",
          tier: "on-level",
          stem: "1+1?",
          choices: ["2", "3"],
          correctIndex: 0,
          explanation: "2",
        },
      ],
    }),
  );
  // A fixture sequence, so this asserts the generator's behaviour rather than
  // the live curriculum's shape: the Pre-Unit's 1-1 → 2-6 adjacency in miniature.
  const sequence = {
    order: ["1-1", "2-6"],
    entries: new Map([
      ["1-1", { id: "1-1", index: 0, paced: true, curriculumUnit: 1, repeatUnitKeys: [] }],
      ["2-6", { id: "2-6", index: 1, paced: true, curriculumUnit: 2, repeatUnitKeys: [] }],
    ]),
    repeats: [],
    unitKeys: ["PRE"],
    unpaced: [],
    unitMemberOrder: new Map(),
  };
  const before = readFileSync(join(dir, "2-6", "config.json"), "utf8");
  const result = generate({ write: false, lessonsDir: dir, bankPath, sequence });
  assert.equal(result.wrote, false);
  assert.ok(result.wouldChange >= 1);
  assert.equal(readFileSync(join(dir, "2-6", "config.json"), "utf8"), before);
  generate({ write: true, lessonsDir: dir, bankPath, sequence });
  const after = JSON.parse(readFileSync(join(dir, "2-6", "config.json"), "utf8"));
  assert.equal(after.warmup.prevLessonId, "1-1");
  assert.equal(after.warmup.reviews, "1-1");
  assert.equal(after.warmup.prevLessonTitle, "Math is Mine");
  rmSync(dir, { recursive: true, force: true });
});
