#!/usr/bin/env node
/* =============================================================================
 * generate-warmups.test.mjs — the lesson sequence must come from disk.
 * -----------------------------------------------------------------------------
 * scripts/generate-warmups.mjs used to carry a hardcoded ALL_LESSON_IDS of 68
 * ids. The tree has 84 whole-group lessons; 23 on disk were missing from the
 * list and 7 in the list were gone (1-7, 4-6..4-9, 9-5, 9-6). For any id not
 * in the list, getPrevLessonId fell through to "return baseId", so a re-run
 * would have made 5-8's warmup review 5-8.
 *
 * Warmups are not regenerated by the build, so this did not corrupt the
 * current configs by itself. It is a landmine: the next person who runs the
 * generator would write the wrong previous lesson into every omitted config.
 * ============================================================================= */
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  getBaseLessonId,
  previousLessonId,
  wholeGroupLessonIds,
} from "../scripts/generate-warmups.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LESSONS = join(ROOT, "lessons");
const SRC = readFileSync(join(ROOT, "scripts/generate-warmups.mjs"), "utf8");

test("importing the generator does not write lesson configs", () => {
  // If the write loop still ran at module load, this file could not import it
  // without mutating the curriculum. The assertion is the import itself.
  assert.ok(typeof wholeGroupLessonIds === "function");
});

test("the generator does not keep a hardcoded lesson-id array", () => {
  assert.doesNotMatch(
    SRC,
    /ALL_LESSON_IDS\s*=\s*\[/,
    "stale hardcoded ALL_LESSON_IDS is how 23 lessons would review themselves",
  );
});

test("whole-group ids are exactly the on-disk lesson folders", () => {
  const fromDisk = readdirSync(LESSONS)
    .filter((d) => existsSync(join(LESSONS, d, "config.json")) && /^\d+-\d+$/.test(d))
    .sort();
  const fromFn = [...wholeGroupLessonIds(LESSONS)].sort();
  assert.deepEqual(fromFn, fromDisk);
  assert.ok(fromDisk.length >= 80, `expected a full Grade 6 set, found ${fromDisk.length}`);
  assert.ok(fromDisk.includes("5-8"), "5-8 exists on disk and must be in the sequence");
  assert.ok(fromDisk.includes("6-13"), "6-13 exists on disk and must be in the sequence");
  assert.ok(!fromDisk.includes("4-9"), "4-9 was removed; a hardcoded list still named it");
});

test("previous lesson is the prior id in book order, not the lesson itself", () => {
  const ids = wholeGroupLessonIds(LESSONS);
  assert.equal(previousLessonId(ids, ids[0]), ids[0], "the first lesson reviews itself");
  const fiveEight = ids.indexOf("5-8");
  assert.ok(fiveEight > 0, "5-8 must be present so this pin stays meaningful");
  assert.equal(previousLessonId(ids, "5-8"), ids[fiveEight - 1]);
  assert.notEqual(previousLessonId(ids, "5-8"), "5-8");
  assert.equal(previousLessonId(ids, "not-a-lesson"), "not-a-lesson");
});

test("variant folders still map to their whole-group id", () => {
  assert.equal(getBaseLessonId("5-8-group1"), "5-8");
  assert.equal(getBaseLessonId("10-1-catchup"), "10-1");
  assert.equal(getBaseLessonId("2-12"), "2-12");
});
