#!/usr/bin/env node
/**
 * validate-catalog.mjs
 *
 * Two failures this gate exists to stop, both of which had already happened:
 *
 *   1. DRIFT — data/catalog.json is generated by scripts/generate-catalog.mjs,
 *      which was wired into no npm script and no build step. It was last
 *      regenerated on 2026-08-10 and had fallen 96 entries behind the repo:
 *      the whole Part 2 wave and every catch-up lesson were missing from the
 *      site's own directory. Nothing noticed, because nothing checked.
 *
 *   2. DEAD LINKS — the catalog is the index /directory/ renders, so a path in
 *      it that no longer exists on disk is a 404 handed to a student from the
 *      one page whose job is finding things.
 *
 * Run: npm run validate:catalog   (fix drift with: npm run generate-catalog)
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const CATALOG = resolve(ROOT, "data", "catalog.json");

const problems = [];

if (!existsSync(CATALOG)) {
  console.error("FAIL data/catalog.json is missing. Run: npm run generate-catalog");
  process.exit(1);
}

const before = readFileSync(CATALOG, "utf8");

// 1. Drift: regenerate and compare. The generator is idempotent by design, so
//    an unchanged repo must reproduce the file byte for byte.
execFileSync(process.execPath, [resolve(ROOT, "scripts", "generate-catalog.mjs")], {
  stdio: "pipe",
});
const after = readFileSync(CATALOG, "utf8");
if (before !== after) {
  const a = JSON.parse(before);
  const b = JSON.parse(after);
  const A = new Set(a.entries.map((e) => e.path));
  const B = new Set(b.entries.map((e) => e.path));
  const added = [...B].filter((p) => !A.has(p));
  const removed = [...A].filter((p) => !B.has(p));
  problems.push(
    `data/catalog.json is stale (${a.total} committed vs ${b.total} on disk; ` +
      `+${added.length} / -${removed.length} paths). Run: npm run generate-catalog`,
  );
  if (added.length) console.error("  would add:   ", added.slice(0, 8).join(", "));
  if (removed.length) console.error("  would remove:", removed.slice(0, 8).join(", "));
}

// 2. Every catalogued path must resolve to a real file.
const catalog = JSON.parse(after);
const missing = [];
for (const e of catalog.entries) {
  const rel = e.path.replace(/^\//, "").replace(/\/$/, "");
  const target = e.path.endsWith("/") ? resolve(ROOT, rel, "index.html") : resolve(ROOT, rel);
  if (!existsSync(target)) missing.push(e.path);
}
if (missing.length) {
  problems.push(`${missing.length} catalogued path(s) have no file on disk`);
  console.error("  " + missing.slice(0, 12).join("\n  "));
}

// 3. Every entry must land in a declared section, or /directory/ silently
//    drops it — invisible, which is the exact failure mode being fixed.
const sectionIds = new Set((catalog.sections || []).map((s) => s.id));
const orphanSections = [
  ...new Set(catalog.entries.map((e) => e.section).filter((s) => !sectionIds.has(s))),
];
if (orphanSections.length) {
  problems.push(
    `entries reference undeclared section(s): ${orphanSections.join(", ")} ` +
      "— add them to SECTION_META in scripts/generate-catalog.mjs",
  );
}

// 4. No answer keys. /directory/ is student-reachable and /games/,
//    /activities/ and /practice/ all 301 into it.
const leaked = catalog.entries.filter((e) => /answer-key|\/answers\//i.test(e.path));
if (leaked.length) {
  problems.push(`${leaked.length} answer key(s) reached the public directory`);
  console.error("  " + leaked.map((e) => e.path).join("\n  "));
}

if (problems.length) {
  console.error("\nvalidate:catalog FAILED");
  for (const p of problems) console.error("  ✗ " + p);
  process.exit(1);
}

console.log(
  `validate:catalog OK — ${catalog.total} entries across ` +
    `${Object.keys(catalog.bySection).length} sections, all paths resolve.`,
);
